### 分进合击出报表

In [2]:
import pandas as pd

In [27]:
 %%html
<style>
/* 本电子讲义使用之CSS */
div.code_cell {
    background-color: #e5f1fe;
}
div.cell.selected {
    background-color: #effee2;
    font-size: 2rem;
    line-height: 2.4rem;
}
div.cell.selected .rendered_html table {
    font-size: 2rem !important;
    line-height: 2.4rem !important;
}
.rendered_html pre code {
    background-color: #C4E4ff;   
    padding: 2px 25px;
}
.rendered_html pre {
    background-color: #99c9ff;
}
div.code_cell .CodeMirror {
    font-size: 2rem !important;
    line-height: 2.4rem !important;
}
.rendered_html img, .rendered_html svg {
    max-width: 60%;
    height: auto;
    float: right;
}

.rendered_html img[src*="#full"], .rendered_html svg[src*="#full"] {
    max-width: 95%;
    height: auto;
}

.rendered_html img[src*="#thumbnail"], .rendered_html svg[src*="#thumbnail"] {
    max-width: 15%;
    height: auto;
}

/* Gradient transparent - color - transparent */
hr {
    border: 0;
    border-bottom: 1px dashed #ccc;
}
.emoticon{
    font-size: 5rem;
    line-height: 4.4rem;
    text-align: center;
    vertical-align: middle;
}
.bg-split_apply_comine {
    width: 500px;     
    height: 300px;
    background: url('02_split-apply-comine_500x300.png') -10px -10px;
    float: right;
}
.bg-comine {
    width: 175px;
    height: 150px;
    background: url('02_split-apply-comine_500x300.png') -280px -80px;
    float: right;
}
.bg-apply {
    width: 155px;
    height: 225px;
    background: url('02_split-apply-comine_500x300.png') -160px -30px;
    float: right;
}
.bg-split {
    width: 205px;
    height: 225px;
    background: url('02_split-apply-comine_500x300.png') -10px -30px;
    float: right;
}
.break {
                   page-break-after: right; 
                   width:700px;
                   clear:both;
}
</style>

In [3]:
df = pd.read_csv ("20春_pandas_week02_hurun_unicorn.tsv", encoding = "utf8", sep="\t")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494 entries, 0 to 493
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   排名            494 non-null    int64
 1   企业名称          494 non-null    object
 2   Company Name  494 non-null    object
 3   估值（亿人民币）      494 non-null    int64
 4   国家            494 non-null    object
 5   城市            494 non-null    object
 6   行业            494 non-null    object
 7   掌门人/创始人       494 non-null    object
 8   成立年份          494 non-null    int64
 9   部分投资机构        494 non-null    object
dtypes: int64(3), object(7)
memory usage: 38.7+ KB

In [4]:
#先行再国 先国再行 先国再城 先行再城

先国再行 = df.groupby ( by = ['国家','行业'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
先行再国 = df.groupby ( by = ['行业', '国家'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
先国再城 = df.groupby ( by = ['国家','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
先行再城 = df.groupby ( by = ['行业','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
display(先国再行)
display(先行再国)
display(先国再城)
display(先行再城)

with pd.ExcelWriter("20春_pandas_week03_hurun_unicorn.xlsx") as writer:
    先国再行.to_excel(writer,sheet_name="先国再行") 
    先行再国.to_excel(writer,sheet_name="先行再国") 
    先国再城.to_excel(writer,sheet_name="先国再城") 
    先国再城.to_excel(writer,sheet_name="先行再城")

           企业名称 估值（亿人民币）              成立年份
             数量       总和          均值    最新    最早
国家   行业
中国   金融科技    22    17960  816.363636  2018  2002
     媒体和娱乐   17     8230  484.117647  2015  2003
美国   云计算     32     6880  215.000000  2015  2000
     共享经济     6     5670  945.000000  2017  2008
     金融科技    21     5020  239.047619  2017  2000
...         ...      ...         ...   ...   ...
日本   区块链      1       70   70.000000  2014  2014
法国   人工智能     1       70   70.000000  2016  2016
     媒体和娱乐    1       70   70.000000  2006  2006
爱沙尼亚 共享经济     1       70   70.000000  2013  2013
法国   健康科技     1       70   70.000000  2013  2013

[103 rows x 5 columns]

           企业名称 估值（亿人民币）              成立年份
             数量       总和          均值    最新    最早
行业    国家
金融科技  中国     22    17960  816.363636  2018  2002
媒体和娱乐 中国     17     8230  484.117647  2015  2003
云计算   美国     32     6880  215.000000  2015  2000
共享经济  美国      6     5670  945.000000  2017  2008
金融科技  美国     21     5020  239.047619  2017  2000
...         ...      ...         ...   ...   ...
房地产科技 菲律宾     1       70   70.000000  2015  2015
物流    哥伦比亚    1       70   70.000000  2016  2016
游戏    印度      1       70   70.000000  2012  2012
消费品   芬兰      1       70   70.000000  2016  2016
金融科技  韩国      1       70   70.000000  2011  2011

[103 rows x 5 columns]

         企业名称 估值（亿人民币）              成立年份
           数量       总和          均值    最新    最早
国家   城市
中国   北京    81    22130  273.209877  2019  2001
美国   旧金山   55    17060  310.181818  2017  2004
中国   杭州    19    13290  699.473684  2015  2000
     上海    47     8990  191.276596  2017  2001
美国   纽约    25     8640  345.600000  2015  2002
...       ...      ...         ...   ...   ...
哥伦比亚 波哥大    1       70   70.000000  2016  2016
美国   盐湖城    1       70   70.000000  2008  2008
     罗利     1       70   70.000000  2011  2011
印度   孟买     1       70   70.000000  2012  2012
美国   半月湾    1       70   70.000000  2014  2014

[121 rows x 5 columns]

            企业名称 估值（亿人民币）               成立年份
              数量       总和           均值    最新    最早
行业    城市
金融科技  杭州       4    10290  2572.500000  2015  2009
媒体和娱乐 北京       7     6890   984.285714  2013  2003
共享经济  北京       5     4040   808.000000  2016  2011
云计算   纽约       4     3950   987.500000  2011  2002
消费品   旧金山      2     3550  1775.000000  2017  2015
...          ...      ...          ...   ...   ...
房地产科技 迈阿密      1       70    70.000000  2013  2013
新能源   坎贝尔      1       70    70.000000  2007  2007
房地产科技 纽约       1       70    70.000000  2012  2012
共享经济  塔林       1       70    70.000000  2013  2013
新能源   布里斯托尔    1       70    70.000000  2009  2009

[298 rows x 5 columns]

In [5]:
# 
先行再城 = df.groupby ( by = ['行业','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \

display(先行再城)

先行再城 = df.groupby ( by = ['行业','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
display(先行再城)

#rename能够更换观察observations对应的标签，可以让使用者换成自己更熟悉的文字，提高表格的可阅读性.

             企业名称 估值（亿人民币）               成立年份
            count      sum         mean   max   min
行业    城市
金融科技  杭州        4    10290  2572.500000  2015  2009
媒体和娱乐 北京        7     6890   984.285714  2013  2003
共享经济  北京        5     4040   808.000000  2016  2011
云计算   纽约        4     3950   987.500000  2011  2002
消费品   旧金山       2     3550  1775.000000  2017  2015
...           ...      ...          ...   ...   ...
房地产科技 迈阿密       1       70    70.000000  2013  2013
新能源   坎贝尔       1       70    70.000000  2007  2007
房地产科技 纽约        1       70    70.000000  2012  2012
共享经济  塔林        1       70    70.000000  2013  2013
新能源   布里斯托尔     1       70    70.000000  2009  2009

[298 rows x 5 columns]

            企业名称 估值（亿人民币）               成立年份
              数量       总和           均值    最新    最早
行业    城市
金融科技  杭州       4    10290  2572.500000  2015  2009
媒体和娱乐 北京       7     6890   984.285714  2013  2003
共享经济  北京       5     4040   808.000000  2016  2011
云计算   纽约       4     3950   987.500000  2011  2002
消费品   旧金山      2     3550  1775.000000  2017  2015
...          ...      ...          ...   ...   ...
房地产科技 迈阿密      1       70    70.000000  2013  2013
新能源   坎贝尔      1       70    70.000000  2007  2007
房地产科技 纽约       1       70    70.000000  2012  2012
共享经济  塔林       1       70    70.000000  2013  2013
新能源   布里斯托尔    1       70    70.000000  2009  2009

[298 rows x 5 columns]

In [6]:
# 更改前
先行再城 = df.groupby ( by = ['行业','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
display(先行再城)

# 更改后
先行再城 = df.groupby ( by = ['行业','城市'] ) \
             .agg ({ "成立年份":["max","min"],
                     "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                                    }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
display(先行再城)

            企业名称 估值（亿人民币）               成立年份
              数量       总和           均值    最新    最早
行业    城市
金融科技  杭州       4    10290  2572.500000  2015  2009
媒体和娱乐 北京       7     6890   984.285714  2013  2003
共享经济  北京       5     4040   808.000000  2016  2011
云计算   纽约       4     3950   987.500000  2011  2002
消费品   旧金山      2     3550  1775.000000  2017  2015
...          ...      ...          ...   ...   ...
房地产科技 迈阿密      1       70    70.000000  2013  2013
新能源   坎贝尔      1       70    70.000000  2007  2007
房地产科技 纽约       1       70    70.000000  2012  2012
共享经济  塔林       1       70    70.000000  2013  2013
新能源   布里斯托尔    1       70    70.000000  2009  2009

[298 rows x 5 columns]

             成立年份       企业名称 估值（亿人民币）
               最新    最早   数量       总和           均值
行业    城市
金融科技  杭州     2015  2009    4    10290  2572.500000
媒体和娱乐 北京     2013  2003    7     6890   984.285714
共享经济  北京     2016  2011    5     4040   808.000000
云计算   纽约     2011  2002    4     3950   987.500000
消费品   旧金山    2017  2015    2     3550  1775.000000
...           ...   ...  ...      ...          ...
房地产科技 迈阿密    2013  2013    1       70    70.000000
新能源   坎贝尔    2007  2007    1       70    70.000000
房地产科技 纽约     2012  2012    1       70    70.000000
共享经济  塔林     2013  2013    1       70    70.000000
新能源   布里斯托尔  2009  2009    1       70    70.000000

[298 rows x 5 columns]

In [7]:
# 修改前
先国再城 = df.groupby ( by = ['国家','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
display(先国再城)

# 修改后
先国再城 = df.groupby ( by = ['国家','城市'] ) \
             .agg ({ "企业名称" : "count", \
                     "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],               }) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )
display(先国再城)

# .sort_values会将数值从高到低依次排列，这使得数据阅读更加轻松

            企业名称 估值（亿人民币）              成立年份
              数量       总和          均值    最新    最早
国家  城市
中国  上海        47     8990  191.276596  2017  2001
    北京        81    22130  273.209877  2019  2001
    南京        11     1550  140.909091  2018  2006
    台北         1       70   70.000000  2006  2006
    天津         3     1100  366.666667  2018  2013
...          ...      ...         ...   ...   ...
西班牙 马德里        1       70   70.000000  2011  2011
阿根廷 布宜诺斯艾利斯    1       70   70.000000  2013  2013
韩国  城南市        1      350  350.000000  2007  2007
    首尔         5     1010  202.000000  2011  2005
马耳他 -          1      150  150.000000  2017  2017

[121 rows x 5 columns]

         企业名称 估值（亿人民币）              成立年份
           数量       总和          均值    最新    最早
国家   城市
中国   北京    81    22130  273.209877  2019  2001
美国   旧金山   55    17060  310.181818  2017  2004
中国   杭州    19    13290  699.473684  2015  2000
     上海    47     8990  191.276596  2017  2001
美国   纽约    25     8640  345.600000  2015  2002
...       ...      ...         ...   ...   ...
哥伦比亚 波哥大    1       70   70.000000  2016  2016
美国   盐湖城    1       70   70.000000  2008  2008
     罗利     1       70   70.000000  2011  2011
印度   孟买     1       70   70.000000  2012  2012
美国   半月湾    1       70   70.000000  2014  2014

[121 rows x 5 columns]

#### 小结
* 报表3剑客:rename,sort_values,agg
* .rename能够更换观察observations对应的标签，可以让使用者换成自己更熟悉的文字，提高表格的可阅读性.
* .sort_values会将数值从高到低依次排列，这使得数据阅读更加轻松.
* .agg能够更换观察observations的排列顺序.

* 代码结尾的/表示这行代码已经结束了，代码后的/能够让机器更容易分析代码

### 分群组

In [8]:
df.head()

,排名,企业名称,Company Name,估值（亿人民币）,国家,城市,行业,掌门人/创始人,成立年份,部分投资机构
0,1,蚂蚁金服,Ant Financial,10000,中国,杭州,金融科技,井贤栋,2014,春华资本、中投海外、红杉资本
1,2,字节跳动,Bytedance,5000,中国,北京,媒体和娱乐,张一鸣,2012,红杉资本、海纳亚洲、纪源资本、启明创投
2,3,滴滴出行,Didi Chuxing,3600,中国,北京,共享经济,程维,2012,腾讯、阿里巴巴、红杉资本、经纬中国、纪源资本
3,4,Infor,Infor,3500,美国,纽约,云计算,Jim Schaper,2002,"Golden Gate Capital, Koch Equity Development"
4,5,JUUL Labs,JUUL Labs,3400,美国,旧金山,消费品,"Adam Bowen, James Monsees, Kevin Burns, Tim Da...",2015,"M13, Timothy Davis, Evolution VC Partners, Tig..."

In [9]:
df_grouped_03 = df.groupby(["国家","城市","行业"])
df_grouped_03.mean()

                      排名    估值（亿人民币）         成立年份
国家  城市  行业
中国  上海  云计算   264.000000   70.000000  2012.000000
        人工智能  222.000000   96.666667  2013.000000
        健康科技  115.333333  323.333333  2011.333333
        共享经济   84.000000  200.000000  2016.000000
        大数据   264.000000   70.000000  2015.000000
...                  ...         ...          ...
韩国  城南市 游戏     50.000000  350.000000  2007.000000
    首尔  物流     84.000000  200.000000  2011.000000
        电子商务  184.333333  246.666667  2008.333333
        金融科技  264.000000   70.000000  2011.000000
马耳他 -   区块链   138.000000  150.000000  2017.000000

[298 rows x 3 columns]

In [10]:
df_grouped_01 = df.groupby("国家")
df_grouped_01.groups

{'中国': Int64Index([  0,   1,   2,   6,  10,  11,  12,  13,  14,  19,
             ...
             481, 482, 483, 484, 485, 486, 487, 488, 490, 491],
            dtype='int64', length=206),
 '以色列': Int64Index([178, 184, 190, 310, 364, 384, 415], dtype='int64'),
 '卢森堡': Int64Index([342], dtype='int64'),
 '印度': Int64Index([ 23,  42,  45,  52,  81, 113, 123, 146, 163, 192, 206, 287, 323,
             347, 361, 410, 422, 425, 432, 437, 465],
            dtype='int64'),
 '印度尼西亚': Int64Index([22, 39, 74, 294], dtype='int64'),
 '哥伦比亚': Int64Index([427], dtype='int64'),
 '巴西': Int64Index([66, 344, 358, 389], dtype='int64'),
 '德国': Int64Index([56, 108, 160, 169, 269, 339, 411], dtype='int64'),
 '新加坡': Int64Index([15, 50], dtype='int64'),
 '日本': Int64Index([202, 388], dtype='int64'),
 '法国': Int64Index([149, 317, 320, 396], dtype='int64'),
 '澳大利亚': Int64Index([88], dtype='int64'),
 '爱尔兰': Int64Index([182], dtype='int64'),
 '爱沙尼亚': Int64Index([290], dtype='int64'),
 '瑞典': Int64Index([62, 196], dtype='int64'),
 '瑞士': Int64Index([36, 167, 400], dtype='int64'),
 '美国': Int64Index([  3,   4,   5,   7,   8,   9,  16,  17,  18,  21,
             ...
             463, 466, 469, 470, 471, 472, 474, 489, 492, 493],
            dtype='int64', length=203),
 '芬兰': Int64Index([349], dtype='int64'),
 '英国': Int64Index([55, 73, 82, 107, 110, 145, 157, 164, 172, 177, 197, 207, 418], dtype='int64'),
 '菲律宾': Int64Index([431], dtype='int64'),
 '西班牙': Int64Index([297], dtype='int64'),
 '阿根廷': Int64Index([281], dtype='int64'),
 '韩国': Int64Index([26, 49, 129, 458, 459, 479], dtype='int64'),
 '马耳他': Int64Index([147], dtype='int64')}

In [11]:
df_grouped_02 = df.groupby("行业")
df_grouped_02.groups

{'3D印刷': Int64Index([155, 165, 335], dtype='int64'),
 '云计算': Int64Index([  3,  70,  88,  92, 119, 142, 170, 174, 178, 180, 182, 183, 190,
             208, 209, 211, 212, 219, 251, 270, 272, 281, 282, 308, 310, 319,
             324, 325, 329, 341, 357, 366, 367, 384, 397, 405, 416, 417, 446,
             460, 464, 467, 470, 474],
            dtype='int64'),
 '人工智能': Int64Index([ 33,  41,  46,  63,  84,  91, 102, 135, 138, 143, 145, 153, 161,
             162, 172, 179, 200, 202, 216, 218, 241, 255, 267, 285, 296, 307,
             315, 337, 396, 401, 402, 403, 414, 415, 436, 444, 450, 456, 463,
             489],
            dtype='int64'),
 '健康科技': Int64Index([ 27,  48,  77,  98, 112, 121, 166, 175, 210, 221, 234, 245, 277,
             279, 295, 298, 305, 320, 326, 344, 345, 356, 380, 398, 412, 424,
             454],
            dtype='int64'),
 '共享经济': Int64Index([  2,   5,   8,  15,  22,  40,  45,  47,  52,  99, 127, 148, 149,
             186, 224, 254, 290, 297, 378, 410, 438, 462],
            dtype='int64'),
 '区块链': Int64Index([19, 29, 53, 87, 90, 147, 150, 167, 226, 289, 388], dtype='int64'),
 '即时通讯': Int64Index([168, 194, 347, 362, 448, 452], dtype='int64'),
 '大数据': Int64Index([ 17,  71,  94, 192, 232, 244, 250, 301, 309, 321, 338, 346, 352,
             372, 385, 394, 451, 461],
            dtype='int64'),
 '媒体和娱乐': Int64Index([  1,  13,  16,  85,  93,  95, 101, 117, 132, 151, 154, 204, 213,
             214, 220, 235, 242, 260, 275, 317, 387, 392, 471, 482],
            dtype='int64'),
 '房地产科技': Int64Index([24, 80, 104, 115, 225, 240, 259, 332, 419, 431, 443, 468, 472], dtype='int64'),
 '教育科技': Int64Index([42, 128, 134, 136, 229, 265, 271, 312, 313, 353, 354, 365, 377,
             466, 490],
            dtype='int64'),
 '新能源': Int64Index([196, 206, 302, 328, 399, 418, 423, 435, 440, 469], dtype='int64'),
 '新能源汽车': Int64Index([54, 59, 78, 79, 120, 133, 152, 158, 223, 227, 249, 292, 351, 381,
             406],
            dtype='int64'),
 '新零售': Int64Index([176, 189, 266, 276, 284, 287, 299, 300, 375, 407, 447], dtype='int64'),
 '机器人': Int64Index([14, 76, 109, 243], dtype='int64'),
 '消费品': Int64Index([4, 69, 195, 198, 205, 217, 257, 343, 349, 420, 442, 455], dtype='int64'),
 '游戏': Int64Index([49, 51, 118, 126, 140, 177, 230, 322, 323], dtype='int64'),
 '物流': Int64Index([ 11,  18,  20,  31,  43,  64,  81,  97, 105, 123, 129, 163, 164,
             171, 181, 201, 222, 246, 248, 278, 311, 334, 358, 371, 374, 379,
             389, 390, 427, 432, 481, 484, 488, 492],
            dtype='int64'),
 '生命科学': Int64Index([ 21,  30,  36,  61,  68, 100, 124, 137, 160, 193, 197, 258, 264,
             340, 355, 364, 408, 441],
            dtype='int64'),
 '电子商务': Int64Index([ 25,  26,  28,  34,  39,  50,  55,  56,  57,  60,  67,  74,  75,
             103, 106, 113, 122, 131, 169, 187, 215, 231, 236, 237, 238, 239,
             247, 253, 256, 262, 269, 280, 286, 291, 294, 303, 304, 330, 331,
             333, 339, 342, 348, 363, 368, 369, 370, 382, 395, 409, 411, 421,
             425, 428, 430, 437, 445, 453, 457, 458, 465, 477, 479, 480, 483,
             485, 491, 493],
            dtype='int64'),
 '网络安全': Int64Index([38, 116, 306, 360, 376, 391, 413], dtype='int64'),
 '航天': Int64Index([7, 111, 433], dtype='int64'),
 '虚拟与增强现实': Int64Index([44, 65, 400], dtype='int64'),
 '软件与服务': Int64Index([130, 139, 141, 184, 203, 228, 233, 252, 261, 293, 314, 316, 336,
             350, 359, 361, 393, 449, 476, 478, 487],
            dtype='int64'),
 '金融科技': Int64Index([  0,   6,   9,  10,  12,  23,  32,  35,  37,  58,  62,  66,  72,
              73,  82,  83,  86,  89,  96, 107, 108, 110, 114, 125, 144, 146,
             156, 157, 159, 173, 185, 188, 191, 199, 207, 263, 268, 273, 274,
             283, 288, 318, 327, 373, 383, 386, 404, 422, 426, 429, 434, 439,
             459, 473, 475, 486],
            dtype='int64')}

In [12]:
df_grouped_03.groups

{('中国', '上海', '云计算'): Int64Index([464], dtype='int64'),
 ('中国', '上海', '人工智能'): Int64Index([218, 285, 402], dtype='int64'),
 ('中国', '上海', '健康科技'): Int64Index([27, 77, 279], dtype='int64'),
 ('中国', '上海', '共享经济'): Int64Index([99], dtype='int64'),
 ('中国', '上海', '大数据'): Int64Index([321], dtype='int64'),
 ('中国', '上海', '媒体和娱乐'): Int64Index([101, 154, 235, 275, 387], dtype='int64'),
 ('中国', '上海', '房地产科技'): Int64Index([240, 468], dtype='int64'),
 ('中国',
  '上海',
  '教育科技'): Int64Index([229, 265, 313, 354, 365, 490], dtype='int64'),
 ('中国', '上海', '新能源'): Int64Index([328], dtype='int64'),
 ('中国', '上海', '新能源汽车'): Int64Index([78, 133, 223], dtype='int64'),
 ('中国', '上海', '消费品'): Int64Index([257], dtype='int64'),
 ('中国', '上海', '物流'): Int64Index([64, 278, 484], dtype='int64'),
 ('中国', '上海', '生命科学'): Int64Index([100, 258], dtype='int64'),
 ('中国',
  '上海',
  '电子商务'): Int64Index([131, 238, 253, 262, 291, 333, 421, 485], dtype='int64'),
 ('中国', '上海', '软件与服务'): Int64Index([130, 139, 476], dtype='int64'),
 ('中国', '上海', '金融科技'): Int64Index([6, 35, 89, 318], dtype='int64'),
 ('中国', '北京', '云计算'): Int64Index([183, 467], dtype='int64'),
 ('中国',
  '北京',
  '人工智能'): Int64Index([46, 63, 102, 153, 241, 267, 337, 401, 403], dtype='int64'),
 ('中国', '北京', '健康科技'): Int64Index([234, 305, 345, 398, 454], dtype='int64'),
 ('中国', '北京', '共享经济'): Int64Index([2, 127, 254, 378, 438], dtype='int64'),
 ('中国', '北京', '区块链'): Int64Index([19], dtype='int64'),
 ('中国', '北京', '大数据'): Int64Index([232, 338, 372, 385, 451], dtype='int64'),
 ('中国',
  '北京',
  '媒体和娱乐'): Int64Index([1, 13, 85, 132, 220, 392, 482], dtype='int64'),
 ('中国', '北京', '房地产科技'): Int64Index([80, 225, 259], dtype='int64'),
 ('中国', '北京', '教育科技'): Int64Index([128, 134, 136, 353, 377], dtype='int64'),
 ('中国', '北京', '新能源汽车'): Int64Index([120, 158], dtype='int64'),
 ('中国', '北京', '消费品'): Int64Index([442], dtype='int64'),
 ('中国', '北京', '游戏'): Int64Index([230], dtype='int64'),
 ('中国', '北京', '物流'): Int64Index([20, 248, 390, 488], dtype='int64'),
 ('中国', '北京', '生命科学'): Int64Index([408, 441], dtype='int64'),
 ('中国',
  '北京',
  '电子商务'): Int64Index([25, 34, 106, 122, 187, 231, 239, 256, 368, 428, 477, 483, 491], dtype='int64'),
 ('中国', '北京', '网络安全'): Int64Index([116], dtype='int64'),
 ('中国',
  '北京',
  '软件与服务'): Int64Index([141, 228, 233, 314, 336, 393, 487], dtype='int64'),
 ('中国',
  '北京',
  '金融科技'): Int64Index([12, 96, 263, 268, 327, 429, 439, 486], dtype='int64'),
 ('中国', '南京', '媒体和娱乐'): Int64Index([214], dtype='int64'),
 ('中国', '南京', '新能源汽车'): Int64Index([152, 249, 292], dtype='int64'),
 ('中国', '南京', '新零售'): Int64Index([299], dtype='int64'),
 ('中国', '南京', '电子商务'): Int64Index([103, 236, 304], dtype='int64'),
 ('中国', '南京', '软件与服务'): Int64Index([350, 359], dtype='int64'),
 ('中国', '南京', '金融科技'): Int64Index([37], dtype='int64'),
 ('中国', '台北', '新能源'): Int64Index([423], dtype='int64'),
 ('中国', '天津', '共享经济'): Int64Index([47], dtype='int64'),
 ('中国', '天津', '房地产科技'): Int64Index([24], dtype='int64'),
 ('中国', '天津', '机器人'): Int64Index([243], dtype='int64'),
 ('中国', '广州', '人工智能'): Int64Index([91], dtype='int64'),
 ('中国', '广州', '健康科技'): Int64Index([356], dtype='int64'),
 ('中国', '广州', '新能源汽车'): Int64Index([79], dtype='int64'),
 ('中国', '广州', '新零售'): Int64Index([189, 407], dtype='int64'),
 ('中国', '广州', '电子商务'): Int64Index([370, 480], dtype='int64'),
 ('中国', '广州', '软件与服务'): Int64Index([478], dtype='int64'),
 ('中国', '张家口', '大数据'): Int64Index([250], dtype='int64'),
 ('中国', '成都', '媒体和娱乐'): Int64Index([260], dtype='int64'),
 ('中国', '成都', '新零售'): Int64Index([266], dtype='int64'),
 ('中国', '成都', '物流'): Int64Index([181, 371], dtype='int64'),
 ('中国', '无锡', '大数据'): Int64Index([352], dtype='int64'),
 ('中国', '杭州', '云计算'): Int64Index([251, 325], dtype='int64'),
 ('中国', '杭州', '人工智能'): Int64Index([255], dtype='int64'),
 ('中国', '杭州', '健康科技'): Int64Index([48, 326], dtype='int64'),
 ('中国', '杭州', '共享经济'): Int64Index([224], dtype='int64'),
 ('中国', '杭州', '区块链'): Int64Index([87, 226], dtype='int64'),
 ('中国', '杭州', '大数据'): Int64Index([244], dtype='int64'),
 ('中国', '杭州', '媒体和娱乐'): Int64Index([242], dtype='int64'),
 ('中国', '杭州', '物流'): Int64Index([11], dtype='int64'),
 ('中国', '杭州', '电子商务'): Int64Index([215, 286, 303, 369], dtype='int64'),
 ('中国', '杭州', '金融科技'): Int64Index([0, 199, 383, 473], dtype='int64'),
 ('中国', '桐乡', '新能源汽车'): Int64Index([351], dtype='int64'),
 ('中国', '武汉', '媒体和娱乐'): Int64Index([95], dtype='int64'),
 ('中国', '深圳', '人工智能'): Int64Index([414], dtype='int64'),
 ('中国', '深圳', '健康科技'): Int64Index([245, 380], dtype='int64'),
 ('中国', '深圳', '媒体和娱乐'): Int64Index([93], dtype='int64'),
 ('中国', '深圳', '房地产科技'): Int64Index([332], dtype='int64'),
 ('中国', '深圳', '机器人'): Int64Index([14, 76], dtype='int64'),
 ('中国', '深圳', '消费品'): Int64Index([69, 205], dtype='int64'),
 ('中国', '深圳', '物流'): Int64Index([105, 334, 481], dtype='int64'),
 ('中国', '深圳', '电子商务'): Int64Index([247], dtype='int64'),
 ('中国', '深圳', '软件与服务'): Int64Index([252], dtype='int64'),
 ('中国', '深圳', '金融科技'): Int64Index([10, 274, 386], dtype='int64'),
 ('中国', '绍兴', '新能源汽车'): Int64Index([227], dtype='int64'),
 ('中国', '贵阳', '物流'): Int64Index([43], dtype='int64'),
 ('中国', '重庆', '电子商务'): Int64Index([363], dtype='int64'),
 ('中国', '重庆', '软件与服务'): Int64Index([261], dtype='int64'),
 ('中国', '金华', '新能源汽车'): Int64Index([381], dtype='int64'),
 ('中国', '青岛', '物流'): Int64Index([246], dtype='int64'),
 ('中国', '香港', '区块链'): Int64Index([150], dtype='int64'),
 ('中国', '香港', '物流'): Int64Index([379], dtype='int64'),
 ('中国', '香港', '电子商务'): Int64Index([237], dtype='int64'),
 ('中国', '香港', '金融科技'): Int64Index([273, 475], dtype='int64'),
 ('以色列', '特拉维夫', '云计算'): Int64Index([178, 190], dtype='int64'),
 ('以色列', '特拉维夫', '生命科学'): Int64Index([364], dtype='int64'),
 ('以色列', '耐斯兹敖那', '云计算'): Int64Index([310], dtype='int64'),
 ('以色列', '耶路撒冷', '云计算'): Int64Index([384], dtype='int64'),
 ('以色列', '耶路撒冷', '人工智能'): Int64Index([415], dtype='int64'),
 ('以色列', '雷霍沃特', '软件与服务'): Int64Index([184], dtype='int64'),
 ('卢森堡', '卢森堡', '电子商务'): Int64Index([342], dtype='int64'),
 ('印度', '古尔冈', '共享经济'): Int64Index([52], dtype='int64'),
 ('印度', '古尔冈', '新能源'): Int64Index([206], dtype='int64'),
 ('印度', '古尔冈', '物流'): Int64Index([81, 163, 432], dtype='int64'),
 ('印度', '古尔冈', '电子商务'): Int64Index([437], dtype='int64'),
 ('印度', '古尔冈', '金融科技'): Int64Index([422], dtype='int64'),
 ('印度', '孟买', '游戏'): Int64Index([323], dtype='int64'),
 ('印度', '新德里', '即时通讯'): Int64Index([347], dtype='int64'),
 ('印度', '班加罗尔', '共享经济'): Int64Index([45, 410], dtype='int64'),
 ('印度', '班加罗尔', '大数据'): Int64Index([192], dtype='int64'),
 ('印度', '班加罗尔', '教育科技'): Int64Index([42], dtype='int64'),
 ('印度', '班加罗尔', '新零售'): Int64Index([287], dtype='int64'),
 ('印度', '班加罗尔', '物流'): Int64Index([123], dtype='int64'),
 ('印度', '班加罗尔', '电子商务'): Int64Index([425, 465], dtype='int64'),
 ('印度', '班加罗尔', '软件与服务'): Int64Index([361], dtype='int64'),
 ('印度', '艾哈迈达巴德', '金融科技'): Int64Index([146], dtype='int64'),
 ('印度', '诺伊达', '电子商务'): Int64Index([113], dtype='int64'),
 ('印度', '诺伊达', '金融科技'): Int64Index([23], dtype='int64'),
 ('印度尼西亚', '雅加达', '共享经济'): Int64Index([22], dtype='int64'),
 ('印度尼西亚', '雅加达', '电子商务'): Int64Index([39, 74, 294], dtype='int64'),
 ('哥伦比亚', '波哥大', '物流'): Int64Index([427], dtype='int64'),
 ('巴西', '圣保罗', '健康科技'): Int64Index([344], dtype='int64'),
 ('巴西', '圣保罗', '物流'): Int64Index([358, 389], dtype='int64'),
 ('巴西', '圣保罗', '金融科技'): Int64Index([66], dtype='int64'),
 ('德国', '巴登符腾堡州', '生命科学'): Int64Index([160], dtype='int64'),
 ('德国', '慕尼黑', '电子商务'): Int64Index([169], dtype='int64'),
 ('德国', '柏林', '电子商务'): Int64Index([56, 339, 411], dtype='int64'),
 ('德国', '柏林', '金融科技'): Int64Index([108], dtype='int64'),
 ('德国', '汉堡', '电子商务'): Int64Index([269], dtype='int64'),
 ('新加坡', '新加坡', '共享经济'): Int64Index([15], dtype='int64'),
 ('新加坡', '新加坡', '电子商务'): Int64Index([50], dtype='int64'),
 ('日本', '东京', '人工智能'): Int64Index([202], dtype='int64'),
 ('日本', '东京', '区块链'): Int64Index([388], dtype='int64'),
 ('法国', '巴黎', '人工智能'): Int64Index([396], dtype='int64'),
 ('法国', '巴黎', '健康科技'): Int64Index([320], dtype='int64'),
 ('法国', '巴黎', '共享经济'): Int64Index([149], dtype='int64'),
 ('法国', '巴黎', '媒体和娱乐'): Int64Index([317], dtype='int64'),
 ('澳大利亚', '悉尼', '云计算'): Int64Index([88], dtype='int64'),
 ('爱尔兰', '都柏林', '云计算'): Int64Index([182], dtype='int64'),
 ('爱沙尼亚', '塔林', '共享经济'): Int64Index([290], dtype='int64'),
 ('瑞典', '斯德哥尔摩', '新能源'): Int64Index([196], dtype='int64'),
 ('瑞典', '斯德哥尔摩', '金融科技'): Int64Index([62], dtype='int64'),
 ('瑞士', '巴塞尔', '生命科学'): Int64Index([36], dtype='int64'),
 ('瑞士', '楚格', '区块链'): Int64Index([167], dtype='int64'),
 ('瑞士', '洛桑市', '虚拟与增强现实'): Int64Index([400], dtype='int64'),
 ('美国', '-', '云计算'): Int64Index([357], dtype='int64'),
 ('美国', '-', '消费品'): Int64Index([217], dtype='int64'),
 ('美国', 'Burlington Massachussets', '3D印刷'): Int64Index([165], dtype='int64'),
 ('美国', 'Emerville', '网络安全'): Int64Index([38], dtype='int64'),
 ('美国', 'Foster City', '人工智能'): Int64Index([135], dtype='int64'),
 ('美国', 'Guilford', '健康科技'): Int64Index([295], dtype='int64'),
 ('美国', 'Harrisburg', '人工智能'): Int64Index([33], dtype='int64'),
 ('美国', 'Plantation', '虚拟与增强现实'): Int64Index([44], dtype='int64'),
 ('美国', 'Stafford', '新能源'): Int64Index([399], dtype='int64'),
 ('美国', '亚特兰大', '健康科技'): Int64Index([210], dtype='int64'),
 ('美国', '亚特兰大', '新能源'): Int64Index([435], dtype='int64'),
 ('美国', '亚特兰大', '网络安全'): Int64Index([413], dtype='int64'),
 ('美国', '亚特兰大', '金融科技'): Int64Index([373], dtype='int64'),
 ('美国', '伯班克', '媒体和娱乐'): Int64Index([213], dtype='int64'),
 ('美国', '克利尔沃特', '网络安全'): Int64Index([376], dtype='int64'),
 ('美国', '加迪纳', '新能源汽车'): Int64Index([59], dtype='int64'),
 ('美国', '匹兹堡', '共享经济'): Int64Index([40], dtype='int64'),
 ('美国', '半月湾', '物流'): Int64Index([492], dtype='int64'),
 ('美国', '华盛顿', '人工智能'): Int64Index([138], dtype='int64'),
 ('美国', '华盛顿', '媒体和娱乐'): Int64Index([471], dtype='int64'),
 ('美国', '卡尔弗城', '新零售'): Int64Index([447], dtype='int64'),
 ('美国', '卡尔弗城', '生命科学'): Int64Index([193], dtype='int64'),
 ('美国', '卡平特里亚', '房地产科技'): Int64Index([115], dtype='int64'),
 ('美国', '哥伦布', '金融科技'): Int64Index([434], dtype='int64'),
 ('美国', '圣何塞', '云计算'): Int64Index([308], dtype='int64'),
 ('美国', '圣何塞', '人工智能'): Int64Index([84], dtype='int64'),
 ('美国', '圣克拉拉', '云计算'): Int64Index([405], dtype='int64'),
 ('美国', '圣克拉拉', '人工智能'): Int64Index([444], dtype='int64'),
 ('美国', '圣卡洛斯', '大数据'): Int64Index([394], dtype='int64'),
 ('美国', '圣地亚哥', '人工智能'): Int64Index([436, 463], dtype='int64'),
 ('美国', '圣地亚哥', '生命科学'): Int64Index([21, 355], dtype='int64'),
 ('美国', '圣塔莫尼卡', '健康科技'): Int64Index([98], dtype='int64'),
 ('美国', '圣塔莫尼卡', '共享经济'): Int64Index([148], dtype='int64'),
 ('美国', '圣塔莫尼卡', '消费品'): Int64Index([455], dtype='int64'),
 ('美国', '圣塔莫尼卡', '电子商务'): Int64Index([331], dtype='int64'),
 ('美国', '圣布鲁诺', '云计算'): Int64Index([170], dtype='int64'),
 ('美国', '圣马特奥', '共享经济'): Int64Index([186], dtype='int64'),
 ('美国', '圣马特奥', '大数据'): Int64Index([71], dtype='int64'),
 ('美国', '圣马特奥', '游戏'): Int64Index([118], dtype='int64'),
 ('美国', '坎布里奇', '人工智能'): Int64Index([161], dtype='int64'),
 ('美国', '坎布里奇', '生命科学'): Int64Index([61], dtype='int64'),
 ('美国', '坎贝尔', '新能源'): Int64Index([302], dtype='int64'),
 ('美国', '埃尔塞贡多', '电子商务'): Int64Index([453], dtype='int64'),
 ('美国', '夏洛特市', '大数据'): Int64Index([461], dtype='int64'),
 ('美国', '夏洛特市', '金融科技'): Int64Index([283], dtype='int64'),
 ('美国', '奥克兰', '金融科技'): Int64Index([188], dtype='int64'),
 ('美国', '奥斯汀', '新零售'): Int64Index([375], dtype='int64'),
 ('美国', '奥斯汀', '金融科技'): Int64Index([191], dtype='int64'),
 ('美国', '尔湾', '健康科技'): Int64Index([277], dtype='int64'),
 ('美国', '山景城', '即时通讯'): Int64Index([452], dtype='int64'),
 ('美国', '山景城', '媒体和娱乐'): Int64Index([204], dtype='int64'),
 ('美国', '山景城', '教育科技'): Int64Index([312, 466], dtype='int64'),
 ('美国', '山景城', '物流'): Int64Index([222], dtype='int64'),
 ('美国', '山景城', '生命科学'): Int64Index([137], dtype='int64'),
 ('美国', '帕洛阿尔托', '云计算'): Int64Index([92], dtype='int64'),
 ('美国', '帕洛阿尔托', '人工智能'): Int64Index([143], dtype='int64'),
 ('美国', '帕洛阿尔托', '即时通讯'): Int64Index([448], dtype='int64'),
 ('美国', '帕洛阿尔托', '大数据'): Int64Index([17], dtype='int64'),
 ('美国', '帕洛阿尔托', '游戏'): Int64Index([51, 140], dtype='int64'),
 ('美国', '帕洛阿尔托', '电子商务'): Int64Index([60, 75], dtype='int64'),
 ('美国', '帕洛阿尔托', '金融科技'): Int64Index([156, 288], dtype='int64'),
 ('美国', '底特律', '电子商务'): Int64Index([445], dtype='int64'),
 ('美国', '斯科茨代尔', '消费品'): Int64Index([195], dtype='int64'),
 ('美国',
  '旧金山',
  '云计算'): Int64Index([70, 119, 142, 174, 208, 219, 272, 282, 319, 341, 397, 460, 470,
             474],
            dtype='int64'),
 ('美国', '旧金山', '人工智能'): Int64Index([307, 450], dtype='int64'),
 ('美国', '旧金山', '健康科技'): Int64Index([298, 412], dtype='int64'),
 ('美国', '旧金山', '共享经济'): Int64Index([5, 462], dtype='int64'),
 ('美国', '旧金山', '区块链'): Int64Index([29, 53, 289], dtype='int64'),
 ('美国', '旧金山', '即时通讯'): Int64Index([168, 194, 362], dtype='int64'),
 ('美国', '旧金山', '大数据'): Int64Index([94], dtype='int64'),
 ('美国', '旧金山', '媒体和娱乐'): Int64Index([117], dtype='int64'),
 ('美国', '旧金山', '房地产科技'): Int64Index([443], dtype='int64'),
 ('美国', '旧金山', '新零售'): Int64Index([276], dtype='int64'),
 ('美国', '旧金山', '机器人'): Int64Index([109], dtype='int64'),
 ('美国', '旧金山', '消费品'): Int64Index([4, 198], dtype='int64'),
 ('美国', '旧金山', '游戏'): Int64Index([126], dtype='int64'),
 ('美国', '旧金山', '物流'): Int64Index([18, 31, 97, 201, 374], dtype='int64'),
 ('美国', '旧金山', '电子商务'): Int64Index([28, 67, 280, 348, 457], dtype='int64'),
 ('美国', '旧金山', '网络安全'): Int64Index([306, 391], dtype='int64'),
 ('美国', '旧金山', '虚拟与增强现实'): Int64Index([65], dtype='int64'),
 ('美国',
  '旧金山',
  '金融科技'): Int64Index([9, 58, 72, 83, 86, 114, 159, 173], dtype='int64'),
 ('美国', '普利茅斯', '新能源汽车'): Int64Index([54], dtype='int64'),
 ('美国', '普若佛市', '人工智能'): Int64Index([179], dtype='int64'),
 ('美国', '普莱森顿', '生命科学'): Int64Index([264], dtype='int64'),
 ('美国', '杭廷顿海滩', '航天'): Int64Index([433], dtype='int64'),
 ('美国', '格兰岱尔市', '云计算'): Int64Index([209], dtype='int64'),
 ('美国', '格兰岱尔市', '教育科技'): Int64Index([271], dtype='int64'),
 ('美国', '森尼维耳市', '云计算'): Int64Index([324, 367], dtype='int64'),
 ('美国', '森尼维耳市', '人工智能'): Int64Index([456], dtype='int64'),
 ('美国', '森尼维耳市', '网络安全'): Int64Index([360], dtype='int64'),
 ('美国', '森尼维耳市', '软件与服务'): Int64Index([203], dtype='int64'),
 ('美国', '沃尔瑟姆', '云计算'): Int64Index([270], dtype='int64'),
 ('美国', '沃尔瑟姆', '健康科技'): Int64Index([166], dtype='int64'),
 ('美国', '波士顿', '云计算'): Int64Index([417], dtype='int64'),
 ('美国', '波士顿', '人工智能'): Int64Index([315], dtype='int64'),
 ('美国', '波士顿', '区块链'): Int64Index([90], dtype='int64'),
 ('美国', '波士顿', '游戏'): Int64Index([322], dtype='int64'),
 ('美国', '波士顿', '生命科学'): Int64Index([340], dtype='int64'),
 ('美国', '波士顿', '电子商务'): Int64Index([330], dtype='int64'),
 ('美国', '波士顿', '软件与服务'): Int64Index([316], dtype='int64'),
 ('美国', '波士顿', '金融科技'): Int64Index([125], dtype='int64'),
 ('美国', '洛杉矶', '媒体和娱乐'): Int64Index([16], dtype='int64'),
 ('美国', '洛杉矶', '电子商务'): Int64Index([493], dtype='int64'),
 ('美国', '洛杉矶', '航天'): Int64Index([7], dtype='int64'),
 ('美国', '盐湖城', '大数据'): Int64Index([346], dtype='int64'),
 ('美国', '纳什维尔', '健康科技'): Int64Index([121], dtype='int64'),
 ('美国', '纽约', '云计算'): Int64Index([3, 180, 211, 212], dtype='int64'),
 ('美国', '纽约', '人工智能'): Int64Index([41, 162, 489], dtype='int64'),
 ('美国', '纽约', '健康科技'): Int64Index([112, 221], dtype='int64'),
 ('美国', '纽约', '共享经济'): Int64Index([8], dtype='int64'),
 ('美国', '纽约', '大数据'): Int64Index([309], dtype='int64'),
 ('美国', '纽约', '媒体和娱乐'): Int64Index([151], dtype='int64'),
 ('美国', '纽约', '房地产科技'): Int64Index([472], dtype='int64'),
 ('美国', '纽约', '新零售'): Int64Index([284, 300], dtype='int64'),
 ('美国', '纽约', '消费品'): Int64Index([343, 420], dtype='int64'),
 ('美国', '纽约', '物流'): Int64Index([171], dtype='int64'),
 ('美国', '纽约', '电子商务'): Int64Index([57, 382, 395, 430], dtype='int64'),
 ('美国', '纽约', '软件与服务'): Int64Index([449], dtype='int64'),
 ('美国', '纽约', '金融科技'): Int64Index([185, 404], dtype='int64'),
 ('美国', '罗利', '大数据'): Int64Index([301], dtype='int64'),
 ('美国', '芝加哥', '人工智能'): Int64Index([216], dtype='int64'),
 ('美国', '芝加哥', '生命科学'): Int64Index([124], dtype='int64'),
 ('美国', '芝加哥', '金融科技'): Int64Index([144, 426], dtype='int64'),
 ('美国', '苗必达', '新能源'): Int64Index([469], dtype='int64'),
 ('美国', '菲尼克斯', '新能源汽车'): Int64Index([406], dtype='int64'),
 ('美国', '菲蒙市', '人工智能'): Int64Index([200], dtype='int64'),
 ('美国', '萨默维尔市', '3D印刷'): Int64Index([335], dtype='int64'),
 ('美国', '西雅图', '云计算'): Int64Index([416], dtype='int64'),
 ('美国', '西雅图', '物流'): Int64Index([311], dtype='int64'),
 ('美国', '贝尔维尤', '电子商务'): Int64Index([409], dtype='int64'),
 ('美国', '达拉斯', '生命科学'): Int64Index([68], dtype='int64'),
 ('美国', '迈阿密', '房地产科技'): Int64Index([419], dtype='int64'),
 ('美国', '门洛帕克', '房地产科技'): Int64Index([104], dtype='int64'),
 ('美国', '门洛帕克', '生命科学'): Int64Index([30], dtype='int64'),
 ('美国', '门洛帕克', '金融科技'): Int64Index([32], dtype='int64'),
 ('美国', '阿拉米达', '新能源'): Int64Index([440], dtype='int64'),
 ('美国', '阿林顿', '航天'): Int64Index([111], dtype='int64'),
 ('美国', '雷德伍德城', '3D印刷'): Int64Index([155], dtype='int64'),
 ('美国', '雷德伍德城', '云计算'): Int64Index([329, 366, 446], dtype='int64'),
 ('美国', '雷德伍德城', '人工智能'): Int64Index([296], dtype='int64'),
 ('美国', '雷德伍德城', '健康科技'): Int64Index([175, 424], dtype='int64'),
 ('美国', '雷德伍德城', '新零售'): Int64Index([176], dtype='int64'),
 ('美国', '雷德伍德城', '软件与服务'): Int64Index([293], dtype='int64'),
 ('芬兰', '赫尔辛基', '消费品'): Int64Index([349], dtype='int64'),
 ('英国', '伦敦', '人工智能'): Int64Index([145], dtype='int64'),
 ('英国', '伦敦', '游戏'): Int64Index([177], dtype='int64'),
 ('英国', '伦敦', '物流'): Int64Index([164], dtype='int64'),
 ('英国', '伦敦', '金融科技'): Int64Index([73, 82, 107, 110, 157, 207], dtype='int64'),
 ('英国', '布里斯托尔', '人工智能'): Int64Index([172], dtype='int64'),
 ('英国', '布里斯托尔', '新能源'): Int64Index([418], dtype='int64'),
 ('英国', '曼彻斯特', '电子商务'): Int64Index([55], dtype='int64'),
 ('英国', '牛津', '生命科学'): Int64Index([197], dtype='int64'),
 ('菲律宾', '马卡迪', '房地产科技'): Int64Index([431], dtype='int64'),
 ('西班牙', '马德里', '共享经济'): Int64Index([297], dtype='int64'),
 ('阿根廷', '布宜诺斯艾利斯', '云计算'): Int64Index([281], dtype='int64'),
 ('韩国', '城南市', '游戏'): Int64Index([49], dtype='int64'),
 ('韩国', '首尔', '物流'): Int64Index([129], dtype='int64'),
 ('韩国', '首尔', '电子商务'): Int64Index([26, 458, 479], dtype='int64'),
 ('韩国', '首尔', '金融科技'): Int64Index([459], dtype='int64'),
 ('马耳他', '-', '区块链'): Int64Index([147], dtype='int64')}

### 进进进

In [14]:
df["估值（亿人民币）"].agg("sum")

117970

In [19]:
df_grouped_03["成立年份"].agg(["max","min"])

               max   min
国家  城市  行业
中国  上海  云计算   2012  2012
        人工智能  2015  2012
        健康科技  2016  2008
        共享经济  2016  2016
        大数据   2015  2015
...            ...   ...
韩国  城南市 游戏    2007  2007
    首尔  物流    2011  2011
        电子商务  2010  2005
        金融科技  2011  2011
马耳他 -   区块链   2017  2017

[298 rows x 2 columns]

In [20]:
df_grouped_03["排名"].agg(["max","min"])

              max  min
国家  城市  行业
中国  上海  云计算   264  264
        人工智能  264  138
        健康科技  264   25
        共享经济   84   84
        大数据   264  264
...           ...  ...
韩国  城南市 游戏     50   50
    首尔  物流     84   84
        电子商务  264   25
        金融科技  264  264
马耳他 -   区块链   138  138

[298 rows x 2 columns]

### 合合合

In [20]:
df.groupby(["国家","行业"])["估值（亿人民币）"].agg(sum = "sum",mean = "mean",count = "count")

           sum        mean  count
国家  行业
中国  云计算    460   92.000000      5
    人工智能  2090  139.333333     15
    健康科技  2060  158.461538     13
    共享经济  4740  592.500000      8
    区块链   1250  312.500000      4
...        ...         ...    ...
韩国  游戏     350  350.000000      1
    物流     200  200.000000      1
    电子商务   740  246.666667      3
    金融科技    70   70.000000      1
马耳他 区块链    150  150.000000      1

[103 rows x 3 columns]

In [22]:
# 该groups属性是一个dict，其键是计算出的唯一组，而对应的值是属于每个组的轴标签。
df_grouped_01.groups

{('中国', '上海', '云计算'): Int64Index([464], dtype='int64'),
 ('中国', '上海', '人工智能'): Int64Index([218, 285, 402], dtype='int64'),
 ('中国', '上海', '健康科技'): Int64Index([27, 77, 279], dtype='int64'),
 ('中国', '上海', '共享经济'): Int64Index([99], dtype='int64'),
 ('中国', '上海', '大数据'): Int64Index([321], dtype='int64'),
 ('中国', '上海', '媒体和娱乐'): Int64Index([101, 154, 235, 275, 387], dtype='int64'),
 ('中国', '上海', '房地产科技'): Int64Index([240, 468], dtype='int64'),
 ('中国',
  '上海',
  '教育科技'): Int64Index([229, 265, 313, 354, 365, 490], dtype='int64'),
 ('中国', '上海', '新能源'): Int64Index([328], dtype='int64'),
 ('中国', '上海', '新能源汽车'): Int64Index([78, 133, 223], dtype='int64'),
 ('中国', '上海', '消费品'): Int64Index([257], dtype='int64'),
 ('中国', '上海', '物流'): Int64Index([64, 278, 484], dtype='int64'),
 ('中国', '上海', '生命科学'): Int64Index([100, 258], dtype='int64'),
 ('中国',
  '上海',
  '电子商务'): Int64Index([131, 238, 253, 262, 291, 333, 421, 485], dtype='int64'),
 ('中国', '上海', '软件与服务'): Int64Index([130, 139, 476], dtype='int64'),
 ('中国', '上海', '金融科技'): Int64Index([6, 35, 89, 318], dtype='int64'),
 ('中国', '北京', '云计算'): Int64Index([183, 467], dtype='int64'),
 ('中国',
  '北京',
  '人工智能'): Int64Index([46, 63, 102, 153, 241, 267, 337, 401, 403], dtype='int64'),
 ('中国', '北京', '健康科技'): Int64Index([234, 305, 345, 398, 454], dtype='int64'),
 ('中国', '北京', '共享经济'): Int64Index([2, 127, 254, 378, 438], dtype='int64'),
 ('中国', '北京', '区块链'): Int64Index([19], dtype='int64'),
 ('中国', '北京', '大数据'): Int64Index([232, 338, 372, 385, 451], dtype='int64'),
 ('中国',
  '北京',
  '媒体和娱乐'): Int64Index([1, 13, 85, 132, 220, 392, 482], dtype='int64'),
 ('中国', '北京', '房地产科技'): Int64Index([80, 225, 259], dtype='int64'),
 ('中国', '北京', '教育科技'): Int64Index([128, 134, 136, 353, 377], dtype='int64'),
 ('中国', '北京', '新能源汽车'): Int64Index([120, 158], dtype='int64'),
 ('中国', '北京', '消费品'): Int64Index([442], dtype='int64'),
 ('中国', '北京', '游戏'): Int64Index([230], dtype='int64'),
 ('中国', '北京', '物流'): Int64Index([20, 248, 390, 488], dtype='int64'),
 ('中国', '北京', '生命科学'): Int64Index([408, 441], dtype='int64'),
 ('中国',
  '北京',
  '电子商务'): Int64Index([25, 34, 106, 122, 187, 231, 239, 256, 368, 428, 477, 483, 491], dtype='int64'),
 ('中国', '北京', '网络安全'): Int64Index([116], dtype='int64'),
 ('中国',
  '北京',
  '软件与服务'): Int64Index([141, 228, 233, 314, 336, 393, 487], dtype='int64'),
 ('中国',
  '北京',
  '金融科技'): Int64Index([12, 96, 263, 268, 327, 429, 439, 486], dtype='int64'),
 ('中国', '南京', '媒体和娱乐'): Int64Index([214], dtype='int64'),
 ('中国', '南京', '新能源汽车'): Int64Index([152, 249, 292], dtype='int64'),
 ('中国', '南京', '新零售'): Int64Index([299], dtype='int64'),
 ('中国', '南京', '电子商务'): Int64Index([103, 236, 304], dtype='int64'),
 ('中国', '南京', '软件与服务'): Int64Index([350, 359], dtype='int64'),
 ('中国', '南京', '金融科技'): Int64Index([37], dtype='int64'),
 ('中国', '台北', '新能源'): Int64Index([423], dtype='int64'),
 ('中国', '天津', '共享经济'): Int64Index([47], dtype='int64'),
 ('中国', '天津', '房地产科技'): Int64Index([24], dtype='int64'),
 ('中国', '天津', '机器人'): Int64Index([243], dtype='int64'),
 ('中国', '广州', '人工智能'): Int64Index([91], dtype='int64'),
 ('中国', '广州', '健康科技'): Int64Index([356], dtype='int64'),
 ('中国', '广州', '新能源汽车'): Int64Index([79], dtype='int64'),
 ('中国', '广州', '新零售'): Int64Index([189, 407], dtype='int64'),
 ('中国', '广州', '电子商务'): Int64Index([370, 480], dtype='int64'),
 ('中国', '广州', '软件与服务'): Int64Index([478], dtype='int64'),
 ('中国', '张家口', '大数据'): Int64Index([250], dtype='int64'),
 ('中国', '成都', '媒体和娱乐'): Int64Index([260], dtype='int64'),
 ('中国', '成都', '新零售'): Int64Index([266], dtype='int64'),
 ('中国', '成都', '物流'): Int64Index([181, 371], dtype='int64'),
 ('中国', '无锡', '大数据'): Int64Index([352], dtype='int64'),
 ('中国', '杭州', '云计算'): Int64Index([251, 325], dtype='int64'),
 ('中国', '杭州', '人工智能'): Int64Index([255], dtype='int64'),
 ('中国', '杭州', '健康科技'): Int64Index([48, 326], dtype='int64'),
 ('中国', '杭州', '共享经济'): Int64Index([224], dtype='int64'),
 ('中国', '杭州', '区块链'): Int64Index([87, 226], dtype='int64'),
 ('中国', '杭州', '大数据'): Int64Index([244], dtype='int64'),
 ('中国', '杭州', '媒体和娱乐'): Int64Index([242], dtype='int64'),
 ('中国', '杭州', '物流'): Int64Index([11], dtype='int64'),
 ('中国', '杭州', '电子商务'): Int64Index([215, 286, 303, 369], dtype='int64'),
 ('中国', '杭州', '金融科技'): Int64Index([0, 199, 383, 473], dtype='int64'),
 ('中国', '桐乡', '新能源汽车'): Int64Index([351], dtype='int64'),
 ('中国', '武汉', '媒体和娱乐'): Int64Index([95], dtype='int64'),
 ('中国', '深圳', '人工智能'): Int64Index([414], dtype='int64'),
 ('中国', '深圳', '健康科技'): Int64Index([245, 380], dtype='int64'),
 ('中国', '深圳', '媒体和娱乐'): Int64Index([93], dtype='int64'),
 ('中国', '深圳', '房地产科技'): Int64Index([332], dtype='int64'),
 ('中国', '深圳', '机器人'): Int64Index([14, 76], dtype='int64'),
 ('中国', '深圳', '消费品'): Int64Index([69, 205], dtype='int64'),
 ('中国', '深圳', '物流'): Int64Index([105, 334, 481], dtype='int64'),
 ('中国', '深圳', '电子商务'): Int64Index([247], dtype='int64'),
 ('中国', '深圳', '软件与服务'): Int64Index([252], dtype='int64'),
 ('中国', '深圳', '金融科技'): Int64Index([10, 274, 386], dtype='int64'),
 ('中国', '绍兴', '新能源汽车'): Int64Index([227], dtype='int64'),
 ('中国', '贵阳', '物流'): Int64Index([43], dtype='int64'),
 ('中国', '重庆', '电子商务'): Int64Index([363], dtype='int64'),
 ('中国', '重庆', '软件与服务'): Int64Index([261], dtype='int64'),
 ('中国', '金华', '新能源汽车'): Int64Index([381], dtype='int64'),
 ('中国', '青岛', '物流'): Int64Index([246], dtype='int64'),
 ('中国', '香港', '区块链'): Int64Index([150], dtype='int64'),
 ('中国', '香港', '物流'): Int64Index([379], dtype='int64'),
 ('中国', '香港', '电子商务'): Int64Index([237], dtype='int64'),
 ('中国', '香港', '金融科技'): Int64Index([273, 475], dtype='int64'),
 ('以色列', '特拉维夫', '云计算'): Int64Index([178, 190], dtype='int64'),
 ('以色列', '特拉维夫', '生命科学'): Int64Index([364], dtype='int64'),
 ('以色列', '耐斯兹敖那', '云计算'): Int64Index([310], dtype='int64'),
 ('以色列', '耶路撒冷', '云计算'): Int64Index([384], dtype='int64'),
 ('以色列', '耶路撒冷', '人工智能'): Int64Index([415], dtype='int64'),
 ('以色列', '雷霍沃特', '软件与服务'): Int64Index([184], dtype='int64'),
 ('卢森堡', '卢森堡', '电子商务'): Int64Index([342], dtype='int64'),
 ('印度', '古尔冈', '共享经济'): Int64Index([52], dtype='int64'),
 ('印度', '古尔冈', '新能源'): Int64Index([206], dtype='int64'),
 ('印度', '古尔冈', '物流'): Int64Index([81, 163, 432], dtype='int64'),
 ('印度', '古尔冈', '电子商务'): Int64Index([437], dtype='int64'),
 ('印度', '古尔冈', '金融科技'): Int64Index([422], dtype='int64'),
 ('印度', '孟买', '游戏'): Int64Index([323], dtype='int64'),
 ('印度', '新德里', '即时通讯'): Int64Index([347], dtype='int64'),
 ('印度', '班加罗尔', '共享经济'): Int64Index([45, 410], dtype='int64'),
 ('印度', '班加罗尔', '大数据'): Int64Index([192], dtype='int64'),
 ('印度', '班加罗尔', '教育科技'): Int64Index([42], dtype='int64'),
 ('印度', '班加罗尔', '新零售'): Int64Index([287], dtype='int64'),
 ('印度', '班加罗尔', '物流'): Int64Index([123], dtype='int64'),
 ('印度', '班加罗尔', '电子商务'): Int64Index([425, 465], dtype='int64'),
 ('印度', '班加罗尔', '软件与服务'): Int64Index([361], dtype='int64'),
 ('印度', '艾哈迈达巴德', '金融科技'): Int64Index([146], dtype='int64'),
 ('印度', '诺伊达', '电子商务'): Int64Index([113], dtype='int64'),
 ('印度', '诺伊达', '金融科技'): Int64Index([23], dtype='int64'),
 ('印度尼西亚', '雅加达', '共享经济'): Int64Index([22], dtype='int64'),
 ('印度尼西亚', '雅加达', '电子商务'): Int64Index([39, 74, 294], dtype='int64'),
 ('哥伦比亚', '波哥大', '物流'): Int64Index([427], dtype='int64'),
 ('巴西', '圣保罗', '健康科技'): Int64Index([344], dtype='int64'),
 ('巴西', '圣保罗', '物流'): Int64Index([358, 389], dtype='int64'),
 ('巴西', '圣保罗', '金融科技'): Int64Index([66], dtype='int64'),
 ('德国', '巴登符腾堡州', '生命科学'): Int64Index([160], dtype='int64'),
 ('德国', '慕尼黑', '电子商务'): Int64Index([169], dtype='int64'),
 ('德国', '柏林', '电子商务'): Int64Index([56, 339, 411], dtype='int64'),
 ('德国', '柏林', '金融科技'): Int64Index([108], dtype='int64'),
 ('德国', '汉堡', '电子商务'): Int64Index([269], dtype='int64'),
 ('新加坡', '新加坡', '共享经济'): Int64Index([15], dtype='int64'),
 ('新加坡', '新加坡', '电子商务'): Int64Index([50], dtype='int64'),
 ('日本', '东京', '人工智能'): Int64Index([202], dtype='int64'),
 ('日本', '东京', '区块链'): Int64Index([388], dtype='int64'),
 ('法国', '巴黎', '人工智能'): Int64Index([396], dtype='int64'),
 ('法国', '巴黎', '健康科技'): Int64Index([320], dtype='int64'),
 ('法国', '巴黎', '共享经济'): Int64Index([149], dtype='int64'),
 ('法国', '巴黎', '媒体和娱乐'): Int64Index([317], dtype='int64'),
 ('澳大利亚', '悉尼', '云计算'): Int64Index([88], dtype='int64'),
 ('爱尔兰', '都柏林', '云计算'): Int64Index([182], dtype='int64'),
 ('爱沙尼亚', '塔林', '共享经济'): Int64Index([290], dtype='int64'),
 ('瑞典', '斯德哥尔摩', '新能源'): Int64Index([196], dtype='int64'),
 ('瑞典', '斯德哥尔摩', '金融科技'): Int64Index([62], dtype='int64'),
 ('瑞士', '巴塞尔', '生命科学'): Int64Index([36], dtype='int64'),
 ('瑞士', '楚格', '区块链'): Int64Index([167], dtype='int64'),
 ('瑞士', '洛桑市', '虚拟与增强现实'): Int64Index([400], dtype='int64'),
 ('美国', '-', '云计算'): Int64Index([357], dtype='int64'),
 ('美国', '-', '消费品'): Int64Index([217], dtype='int64'),
 ('美国', 'Burlington Massachussets', '3D印刷'): Int64Index([165], dtype='int64'),
 ('美国', 'Emerville', '网络安全'): Int64Index([38], dtype='int64'),
 ('美国', 'Foster City', '人工智能'): Int64Index([135], dtype='int64'),
 ('美国', 'Guilford', '健康科技'): Int64Index([295], dtype='int64'),
 ('美国', 'Harrisburg', '人工智能'): Int64Index([33], dtype='int64'),
 ('美国', 'Plantation', '虚拟与增强现实'): Int64Index([44], dtype='int64'),
 ('美国', 'Stafford', '新能源'): Int64Index([399], dtype='int64'),
 ('美国', '亚特兰大', '健康科技'): Int64Index([210], dtype='int64'),
 ('美国', '亚特兰大', '新能源'): Int64Index([435], dtype='int64'),
 ('美国', '亚特兰大', '网络安全'): Int64Index([413], dtype='int64'),
 ('美国', '亚特兰大', '金融科技'): Int64Index([373], dtype='int64'),
 ('美国', '伯班克', '媒体和娱乐'): Int64Index([213], dtype='int64'),
 ('美国', '克利尔沃特', '网络安全'): Int64Index([376], dtype='int64'),
 ('美国', '加迪纳', '新能源汽车'): Int64Index([59], dtype='int64'),
 ('美国', '匹兹堡', '共享经济'): Int64Index([40], dtype='int64'),
 ('美国', '半月湾', '物流'): Int64Index([492], dtype='int64'),
 ('美国', '华盛顿', '人工智能'): Int64Index([138], dtype='int64'),
 ('美国', '华盛顿', '媒体和娱乐'): Int64Index([471], dtype='int64'),
 ('美国', '卡尔弗城', '新零售'): Int64Index([447], dtype='int64'),
 ('美国', '卡尔弗城', '生命科学'): Int64Index([193], dtype='int64'),
 ('美国', '卡平特里亚', '房地产科技'): Int64Index([115], dtype='int64'),
 ('美国', '哥伦布', '金融科技'): Int64Index([434], dtype='int64'),
 ('美国', '圣何塞', '云计算'): Int64Index([308], dtype='int64'),
 ('美国', '圣何塞', '人工智能'): Int64Index([84], dtype='int64'),
 ('美国', '圣克拉拉', '云计算'): Int64Index([405], dtype='int64'),
 ('美国', '圣克拉拉', '人工智能'): Int64Index([444], dtype='int64'),
 ('美国', '圣卡洛斯', '大数据'): Int64Index([394], dtype='int64'),
 ('美国', '圣地亚哥', '人工智能'): Int64Index([436, 463], dtype='int64'),
 ('美国', '圣地亚哥', '生命科学'): Int64Index([21, 355], dtype='int64'),
 ('美国', '圣塔莫尼卡', '健康科技'): Int64Index([98], dtype='int64'),
 ('美国', '圣塔莫尼卡', '共享经济'): Int64Index([148], dtype='int64'),
 ('美国', '圣塔莫尼卡', '消费品'): Int64Index([455], dtype='int64'),
 ('美国', '圣塔莫尼卡', '电子商务'): Int64Index([331], dtype='int64'),
 ('美国', '圣布鲁诺', '云计算'): Int64Index([170], dtype='int64'),
 ('美国', '圣马特奥', '共享经济'): Int64Index([186], dtype='int64'),
 ('美国', '圣马特奥', '大数据'): Int64Index([71], dtype='int64'),
 ('美国', '圣马特奥', '游戏'): Int64Index([118], dtype='int64'),
 ('美国', '坎布里奇', '人工智能'): Int64Index([161], dtype='int64'),
 ('美国', '坎布里奇', '生命科学'): Int64Index([61], dtype='int64'),
 ('美国', '坎贝尔', '新能源'): Int64Index([302], dtype='int64'),
 ('美国', '埃尔塞贡多', '电子商务'): Int64Index([453], dtype='int64'),
 ('美国', '夏洛特市', '大数据'): Int64Index([461], dtype='int64'),
 ('美国', '夏洛特市', '金融科技'): Int64Index([283], dtype='int64'),
 ('美国', '奥克兰', '金融科技'): Int64Index([188], dtype='int64'),
 ('美国', '奥斯汀', '新零售'): Int64Index([375], dtype='int64'),
 ('美国', '奥斯汀', '金融科技'): Int64Index([191], dtype='int64'),
 ('美国', '尔湾', '健康科技'): Int64Index([277], dtype='int64'),
 ('美国', '山景城', '即时通讯'): Int64Index([452], dtype='int64'),
 ('美国', '山景城', '媒体和娱乐'): Int64Index([204], dtype='int64'),
 ('美国', '山景城', '教育科技'): Int64Index([312, 466], dtype='int64'),
 ('美国', '山景城', '物流'): Int64Index([222], dtype='int64'),
 ('美国', '山景城', '生命科学'): Int64Index([137], dtype='int64'),
 ('美国', '帕洛阿尔托', '云计算'): Int64Index([92], dtype='int64'),
 ('美国', '帕洛阿尔托', '人工智能'): Int64Index([143], dtype='int64'),
 ('美国', '帕洛阿尔托', '即时通讯'): Int64Index([448], dtype='int64'),
 ('美国', '帕洛阿尔托', '大数据'): Int64Index([17], dtype='int64'),
 ('美国', '帕洛阿尔托', '游戏'): Int64Index([51, 140], dtype='int64'),
 ('美国', '帕洛阿尔托', '电子商务'): Int64Index([60, 75], dtype='int64'),
 ('美国', '帕洛阿尔托', '金融科技'): Int64Index([156, 288], dtype='int64'),
 ('美国', '底特律', '电子商务'): Int64Index([445], dtype='int64'),
 ('美国', '斯科茨代尔', '消费品'): Int64Index([195], dtype='int64'),
 ('美国',
  '旧金山',
  '云计算'): Int64Index([70, 119, 142, 174, 208, 219, 272, 282, 319, 341, 397, 460, 470,
             474],
            dtype='int64'),
 ('美国', '旧金山', '人工智能'): Int64Index([307, 450], dtype='int64'),
 ('美国', '旧金山', '健康科技'): Int64Index([298, 412], dtype='int64'),
 ('美国', '旧金山', '共享经济'): Int64Index([5, 462], dtype='int64'),
 ('美国', '旧金山', '区块链'): Int64Index([29, 53, 289], dtype='int64'),
 ('美国', '旧金山', '即时通讯'): Int64Index([168, 194, 362], dtype='int64'),
 ('美国', '旧金山', '大数据'): Int64Index([94], dtype='int64'),
 ('美国', '旧金山', '媒体和娱乐'): Int64Index([117], dtype='int64'),
 ('美国', '旧金山', '房地产科技'): Int64Index([443], dtype='int64'),
 ('美国', '旧金山', '新零售'): Int64Index([276], dtype='int64'),
 ('美国', '旧金山', '机器人'): Int64Index([109], dtype='int64'),
 ('美国', '旧金山', '消费品'): Int64Index([4, 198], dtype='int64'),
 ('美国', '旧金山', '游戏'): Int64Index([126], dtype='int64'),
 ('美国', '旧金山', '物流'): Int64Index([18, 31, 97, 201, 374], dtype='int64'),
 ('美国', '旧金山', '电子商务'): Int64Index([28, 67, 280, 348, 457], dtype='int64'),
 ('美国', '旧金山', '网络安全'): Int64Index([306, 391], dtype='int64'),
 ('美国', '旧金山', '虚拟与增强现实'): Int64Index([65], dtype='int64'),
 ('美国',
  '旧金山',
  '金融科技'): Int64Index([9, 58, 72, 83, 86, 114, 159, 173], dtype='int64'),
 ('美国', '普利茅斯', '新能源汽车'): Int64Index([54], dtype='int64'),
 ('美国', '普若佛市', '人工智能'): Int64Index([179], dtype='int64'),
 ('美国', '普莱森顿', '生命科学'): Int64Index([264], dtype='int64'),
 ('美国', '杭廷顿海滩', '航天'): Int64Index([433], dtype='int64'),
 ('美国', '格兰岱尔市', '云计算'): Int64Index([209], dtype='int64'),
 ('美国', '格兰岱尔市', '教育科技'): Int64Index([271], dtype='int64'),
 ('美国', '森尼维耳市', '云计算'): Int64Index([324, 367], dtype='int64'),
 ('美国', '森尼维耳市', '人工智能'): Int64Index([456], dtype='int64'),
 ('美国', '森尼维耳市', '网络安全'): Int64Index([360], dtype='int64'),
 ('美国', '森尼维耳市', '软件与服务'): Int64Index([203], dtype='int64'),
 ('美国', '沃尔瑟姆', '云计算'): Int64Index([270], dtype='int64'),
 ('美国', '沃尔瑟姆', '健康科技'): Int64Index([166], dtype='int64'),
 ('美国', '波士顿', '云计算'): Int64Index([417], dtype='int64'),
 ('美国', '波士顿', '人工智能'): Int64Index([315], dtype='int64'),
 ('美国', '波士顿', '区块链'): Int64Index([90], dtype='int64'),
 ('美国', '波士顿', '游戏'): Int64Index([322], dtype='int64'),
 ('美国', '波士顿', '生命科学'): Int64Index([340], dtype='int64'),
 ('美国', '波士顿', '电子商务'): Int64Index([330], dtype='int64'),
 ('美国', '波士顿', '软件与服务'): Int64Index([316], dtype='int64'),
 ('美国', '波士顿', '金融科技'): Int64Index([125], dtype='int64'),
 ('美国', '洛杉矶', '媒体和娱乐'): Int64Index([16], dtype='int64'),
 ('美国', '洛杉矶', '电子商务'): Int64Index([493], dtype='int64'),
 ('美国', '洛杉矶', '航天'): Int64Index([7], dtype='int64'),
 ('美国', '盐湖城', '大数据'): Int64Index([346], dtype='int64'),
 ('美国', '纳什维尔', '健康科技'): Int64Index([121], dtype='int64'),
 ('美国', '纽约', '云计算'): Int64Index([3, 180, 211, 212], dtype='int64'),
 ('美国', '纽约', '人工智能'): Int64Index([41, 162, 489], dtype='int64'),
 ('美国', '纽约', '健康科技'): Int64Index([112, 221], dtype='int64'),
 ('美国', '纽约', '共享经济'): Int64Index([8], dtype='int64'),
 ('美国', '纽约', '大数据'): Int64Index([309], dtype='int64'),
 ('美国', '纽约', '媒体和娱乐'): Int64Index([151], dtype='int64'),
 ('美国', '纽约', '房地产科技'): Int64Index([472], dtype='int64'),
 ('美国', '纽约', '新零售'): Int64Index([284, 300], dtype='int64'),
 ('美国', '纽约', '消费品'): Int64Index([343, 420], dtype='int64'),
 ('美国', '纽约', '物流'): Int64Index([171], dtype='int64'),
 ('美国', '纽约', '电子商务'): Int64Index([57, 382, 395, 430], dtype='int64'),
 ('美国', '纽约', '软件与服务'): Int64Index([449], dtype='int64'),
 ('美国', '纽约', '金融科技'): Int64Index([185, 404], dtype='int64'),
 ('美国', '罗利', '大数据'): Int64Index([301], dtype='int64'),
 ('美国', '芝加哥', '人工智能'): Int64Index([216], dtype='int64'),
 ('美国', '芝加哥', '生命科学'): Int64Index([124], dtype='int64'),
 ('美国', '芝加哥', '金融科技'): Int64Index([144, 426], dtype='int64'),
 ('美国', '苗必达', '新能源'): Int64Index([469], dtype='int64'),
 ('美国', '菲尼克斯', '新能源汽车'): Int64Index([406], dtype='int64'),
 ('美国', '菲蒙市', '人工智能'): Int64Index([200], dtype='int64'),
 ('美国', '萨默维尔市', '3D印刷'): Int64Index([335], dtype='int64'),
 ('美国', '西雅图', '云计算'): Int64Index([416], dtype='int64'),
 ('美国', '西雅图', '物流'): Int64Index([311], dtype='int64'),
 ('美国', '贝尔维尤', '电子商务'): Int64Index([409], dtype='int64'),
 ('美国', '达拉斯', '生命科学'): Int64Index([68], dtype='int64'),
 ('美国', '迈阿密', '房地产科技'): Int64Index([419], dtype='int64'),
 ('美国', '门洛帕克', '房地产科技'): Int64Index([104], dtype='int64'),
 ('美国', '门洛帕克', '生命科学'): Int64Index([30], dtype='int64'),
 ('美国', '门洛帕克', '金融科技'): Int64Index([32], dtype='int64'),
 ('美国', '阿拉米达', '新能源'): Int64Index([440], dtype='int64'),
 ('美国', '阿林顿', '航天'): Int64Index([111], dtype='int64'),
 ('美国', '雷德伍德城', '3D印刷'): Int64Index([155], dtype='int64'),
 ('美国', '雷德伍德城', '云计算'): Int64Index([329, 366, 446], dtype='int64'),
 ('美国', '雷德伍德城', '人工智能'): Int64Index([296], dtype='int64'),
 ('美国', '雷德伍德城', '健康科技'): Int64Index([175, 424], dtype='int64'),
 ('美国', '雷德伍德城', '新零售'): Int64Index([176], dtype='int64'),
 ('美国', '雷德伍德城', '软件与服务'): Int64Index([293], dtype='int64'),
 ('芬兰', '赫尔辛基', '消费品'): Int64Index([349], dtype='int64'),
 ('英国', '伦敦', '人工智能'): Int64Index([145], dtype='int64'),
 ('英国', '伦敦', '游戏'): Int64Index([177], dtype='int64'),
 ('英国', '伦敦', '物流'): Int64Index([164], dtype='int64'),
 ('英国', '伦敦', '金融科技'): Int64Index([73, 82, 107, 110, 157, 207], dtype='int64'),
 ('英国', '布里斯托尔', '人工智能'): Int64Index([172], dtype='int64'),
 ('英国', '布里斯托尔', '新能源'): Int64Index([418], dtype='int64'),
 ('英国', '曼彻斯特', '电子商务'): Int64Index([55], dtype='int64'),
 ('英国', '牛津', '生命科学'): Int64Index([197], dtype='int64'),
 ('菲律宾', '马卡迪', '房地产科技'): Int64Index([431], dtype='int64'),
 ('西班牙', '马德里', '共享经济'): Int64Index([297], dtype='int64'),
 ('阿根廷', '布宜诺斯艾利斯', '云计算'): Int64Index([281], dtype='int64'),
 ('韩国', '城南市', '游戏'): Int64Index([49], dtype='int64'),
 ('韩国', '首尔', '物流'): Int64Index([129], dtype='int64'),
 ('韩国', '首尔', '电子商务'): Int64Index([26, 458, 479], dtype='int64'),
 ('韩国', '首尔', '金融科技'): Int64Index([459], dtype='int64'),
 ('马耳他', '-', '区块链'): Int64Index([147], dtype='int64')}

In [24]:
df_grouped_02.groups

{'3D印刷': Int64Index([155, 165, 335], dtype='int64'),
 '云计算': Int64Index([  3,  70,  88,  92, 119, 142, 170, 174, 178, 180, 182, 183, 190,
             208, 209, 211, 212, 219, 251, 270, 272, 281, 282, 308, 310, 319,
             324, 325, 329, 341, 357, 366, 367, 384, 397, 405, 416, 417, 446,
             460, 464, 467, 470, 474],
            dtype='int64'),
 '人工智能': Int64Index([ 33,  41,  46,  63,  84,  91, 102, 135, 138, 143, 145, 153, 161,
             162, 172, 179, 200, 202, 216, 218, 241, 255, 267, 285, 296, 307,
             315, 337, 396, 401, 402, 403, 414, 415, 436, 444, 450, 456, 463,
             489],
            dtype='int64'),
 '健康科技': Int64Index([ 27,  48,  77,  98, 112, 121, 166, 175, 210, 221, 234, 245, 277,
             279, 295, 298, 305, 320, 326, 344, 345, 356, 380, 398, 412, 424,
             454],
            dtype='int64'),
 '共享经济': Int64Index([  2,   5,   8,  15,  22,  40,  45,  47,  52,  99, 127, 148, 149,
             186, 224, 254, 290, 297, 378, 410, 438, 462],
            dtype='int64'),
 '区块链': Int64Index([19, 29, 53, 87, 90, 147, 150, 167, 226, 289, 388], dtype='int64'),
 '即时通讯': Int64Index([168, 194, 347, 362, 448, 452], dtype='int64'),
 '大数据': Int64Index([ 17,  71,  94, 192, 232, 244, 250, 301, 309, 321, 338, 346, 352,
             372, 385, 394, 451, 461],
            dtype='int64'),
 '媒体和娱乐': Int64Index([  1,  13,  16,  85,  93,  95, 101, 117, 132, 151, 154, 204, 213,
             214, 220, 235, 242, 260, 275, 317, 387, 392, 471, 482],
            dtype='int64'),
 '房地产科技': Int64Index([24, 80, 104, 115, 225, 240, 259, 332, 419, 431, 443, 468, 472], dtype='int64'),
 '教育科技': Int64Index([42, 128, 134, 136, 229, 265, 271, 312, 313, 353, 354, 365, 377,
             466, 490],
            dtype='int64'),
 '新能源': Int64Index([196, 206, 302, 328, 399, 418, 423, 435, 440, 469], dtype='int64'),
 '新能源汽车': Int64Index([54, 59, 78, 79, 120, 133, 152, 158, 223, 227, 249, 292, 351, 381,
             406],
            dtype='int64'),
 '新零售': Int64Index([176, 189, 266, 276, 284, 287, 299, 300, 375, 407, 447], dtype='int64'),
 '机器人': Int64Index([14, 76, 109, 243], dtype='int64'),
 '消费品': Int64Index([4, 69, 195, 198, 205, 217, 257, 343, 349, 420, 442, 455], dtype='int64'),
 '游戏': Int64Index([49, 51, 118, 126, 140, 177, 230, 322, 323], dtype='int64'),
 '物流': Int64Index([ 11,  18,  20,  31,  43,  64,  81,  97, 105, 123, 129, 163, 164,
             171, 181, 201, 222, 246, 248, 278, 311, 334, 358, 371, 374, 379,
             389, 390, 427, 432, 481, 484, 488, 492],
            dtype='int64'),
 '生命科学': Int64Index([ 21,  30,  36,  61,  68, 100, 124, 137, 160, 193, 197, 258, 264,
             340, 355, 364, 408, 441],
            dtype='int64'),
 '电子商务': Int64Index([ 25,  26,  28,  34,  39,  50,  55,  56,  57,  60,  67,  74,  75,
             103, 106, 113, 122, 131, 169, 187, 215, 231, 236, 237, 238, 239,
             247, 253, 256, 262, 269, 280, 286, 291, 294, 303, 304, 330, 331,
             333, 339, 342, 348, 363, 368, 369, 370, 382, 395, 409, 411, 421,
             425, 428, 430, 437, 445, 453, 457, 458, 465, 477, 479, 480, 483,
             485, 491, 493],
            dtype='int64'),
 '网络安全': Int64Index([38, 116, 306, 360, 376, 391, 413], dtype='int64'),
 '航天': Int64Index([7, 111, 433], dtype='int64'),
 '虚拟与增强现实': Int64Index([44, 65, 400], dtype='int64'),
 '软件与服务': Int64Index([130, 139, 141, 184, 203, 228, 233, 252, 261, 293, 314, 316, 336,
             350, 359, 361, 393, 449, 476, 478, 487],
            dtype='int64'),
 '金融科技': Int64Index([  0,   6,   9,  10,  12,  23,  32,  35,  37,  58,  62,  66,  72,
              73,  82,  83,  86,  89,  96, 107, 108, 110, 114, 125, 144, 146,
             156, 157, 159, 173, 185, 188, 191, 199, 207, 263, 268, 273, 274,
             283, 288, 318, 327, 373, 383, 386, 404, 422, 426, 429, 434, 439,
             459, 473, 475, 486],
            dtype='int64')}

In [25]:
df_grouped_03.groups

{('中国', '上海', '云计算'): Int64Index([464], dtype='int64'),
 ('中国', '上海', '人工智能'): Int64Index([218, 285, 402], dtype='int64'),
 ('中国', '上海', '健康科技'): Int64Index([27, 77, 279], dtype='int64'),
 ('中国', '上海', '共享经济'): Int64Index([99], dtype='int64'),
 ('中国', '上海', '大数据'): Int64Index([321], dtype='int64'),
 ('中国', '上海', '媒体和娱乐'): Int64Index([101, 154, 235, 275, 387], dtype='int64'),
 ('中国', '上海', '房地产科技'): Int64Index([240, 468], dtype='int64'),
 ('中国',
  '上海',
  '教育科技'): Int64Index([229, 265, 313, 354, 365, 490], dtype='int64'),
 ('中国', '上海', '新能源'): Int64Index([328], dtype='int64'),
 ('中国', '上海', '新能源汽车'): Int64Index([78, 133, 223], dtype='int64'),
 ('中国', '上海', '消费品'): Int64Index([257], dtype='int64'),
 ('中国', '上海', '物流'): Int64Index([64, 278, 484], dtype='int64'),
 ('中国', '上海', '生命科学'): Int64Index([100, 258], dtype='int64'),
 ('中国',
  '上海',
  '电子商务'): Int64Index([131, 238, 253, 262, 291, 333, 421, 485], dtype='int64'),
 ('中国', '上海', '软件与服务'): Int64Index([130, 139, 476], dtype='int64'),
 ('中国', '上海', '金融科技'): Int64Index([6, 35, 89, 318], dtype='int64'),
 ('中国', '北京', '云计算'): Int64Index([183, 467], dtype='int64'),
 ('中国',
  '北京',
  '人工智能'): Int64Index([46, 63, 102, 153, 241, 267, 337, 401, 403], dtype='int64'),
 ('中国', '北京', '健康科技'): Int64Index([234, 305, 345, 398, 454], dtype='int64'),
 ('中国', '北京', '共享经济'): Int64Index([2, 127, 254, 378, 438], dtype='int64'),
 ('中国', '北京', '区块链'): Int64Index([19], dtype='int64'),
 ('中国', '北京', '大数据'): Int64Index([232, 338, 372, 385, 451], dtype='int64'),
 ('中国',
  '北京',
  '媒体和娱乐'): Int64Index([1, 13, 85, 132, 220, 392, 482], dtype='int64'),
 ('中国', '北京', '房地产科技'): Int64Index([80, 225, 259], dtype='int64'),
 ('中国', '北京', '教育科技'): Int64Index([128, 134, 136, 353, 377], dtype='int64'),
 ('中国', '北京', '新能源汽车'): Int64Index([120, 158], dtype='int64'),
 ('中国', '北京', '消费品'): Int64Index([442], dtype='int64'),
 ('中国', '北京', '游戏'): Int64Index([230], dtype='int64'),
 ('中国', '北京', '物流'): Int64Index([20, 248, 390, 488], dtype='int64'),
 ('中国', '北京', '生命科学'): Int64Index([408, 441], dtype='int64'),
 ('中国',
  '北京',
  '电子商务'): Int64Index([25, 34, 106, 122, 187, 231, 239, 256, 368, 428, 477, 483, 491], dtype='int64'),
 ('中国', '北京', '网络安全'): Int64Index([116], dtype='int64'),
 ('中国',
  '北京',
  '软件与服务'): Int64Index([141, 228, 233, 314, 336, 393, 487], dtype='int64'),
 ('中国',
  '北京',
  '金融科技'): Int64Index([12, 96, 263, 268, 327, 429, 439, 486], dtype='int64'),
 ('中国', '南京', '媒体和娱乐'): Int64Index([214], dtype='int64'),
 ('中国', '南京', '新能源汽车'): Int64Index([152, 249, 292], dtype='int64'),
 ('中国', '南京', '新零售'): Int64Index([299], dtype='int64'),
 ('中国', '南京', '电子商务'): Int64Index([103, 236, 304], dtype='int64'),
 ('中国', '南京', '软件与服务'): Int64Index([350, 359], dtype='int64'),
 ('中国', '南京', '金融科技'): Int64Index([37], dtype='int64'),
 ('中国', '台北', '新能源'): Int64Index([423], dtype='int64'),
 ('中国', '天津', '共享经济'): Int64Index([47], dtype='int64'),
 ('中国', '天津', '房地产科技'): Int64Index([24], dtype='int64'),
 ('中国', '天津', '机器人'): Int64Index([243], dtype='int64'),
 ('中国', '广州', '人工智能'): Int64Index([91], dtype='int64'),
 ('中国', '广州', '健康科技'): Int64Index([356], dtype='int64'),
 ('中国', '广州', '新能源汽车'): Int64Index([79], dtype='int64'),
 ('中国', '广州', '新零售'): Int64Index([189, 407], dtype='int64'),
 ('中国', '广州', '电子商务'): Int64Index([370, 480], dtype='int64'),
 ('中国', '广州', '软件与服务'): Int64Index([478], dtype='int64'),
 ('中国', '张家口', '大数据'): Int64Index([250], dtype='int64'),
 ('中国', '成都', '媒体和娱乐'): Int64Index([260], dtype='int64'),
 ('中国', '成都', '新零售'): Int64Index([266], dtype='int64'),
 ('中国', '成都', '物流'): Int64Index([181, 371], dtype='int64'),
 ('中国', '无锡', '大数据'): Int64Index([352], dtype='int64'),
 ('中国', '杭州', '云计算'): Int64Index([251, 325], dtype='int64'),
 ('中国', '杭州', '人工智能'): Int64Index([255], dtype='int64'),
 ('中国', '杭州', '健康科技'): Int64Index([48, 326], dtype='int64'),
 ('中国', '杭州', '共享经济'): Int64Index([224], dtype='int64'),
 ('中国', '杭州', '区块链'): Int64Index([87, 226], dtype='int64'),
 ('中国', '杭州', '大数据'): Int64Index([244], dtype='int64'),
 ('中国', '杭州', '媒体和娱乐'): Int64Index([242], dtype='int64'),
 ('中国', '杭州', '物流'): Int64Index([11], dtype='int64'),
 ('中国', '杭州', '电子商务'): Int64Index([215, 286, 303, 369], dtype='int64'),
 ('中国', '杭州', '金融科技'): Int64Index([0, 199, 383, 473], dtype='int64'),
 ('中国', '桐乡', '新能源汽车'): Int64Index([351], dtype='int64'),
 ('中国', '武汉', '媒体和娱乐'): Int64Index([95], dtype='int64'),
 ('中国', '深圳', '人工智能'): Int64Index([414], dtype='int64'),
 ('中国', '深圳', '健康科技'): Int64Index([245, 380], dtype='int64'),
 ('中国', '深圳', '媒体和娱乐'): Int64Index([93], dtype='int64'),
 ('中国', '深圳', '房地产科技'): Int64Index([332], dtype='int64'),
 ('中国', '深圳', '机器人'): Int64Index([14, 76], dtype='int64'),
 ('中国', '深圳', '消费品'): Int64Index([69, 205], dtype='int64'),
 ('中国', '深圳', '物流'): Int64Index([105, 334, 481], dtype='int64'),
 ('中国', '深圳', '电子商务'): Int64Index([247], dtype='int64'),
 ('中国', '深圳', '软件与服务'): Int64Index([252], dtype='int64'),
 ('中国', '深圳', '金融科技'): Int64Index([10, 274, 386], dtype='int64'),
 ('中国', '绍兴', '新能源汽车'): Int64Index([227], dtype='int64'),
 ('中国', '贵阳', '物流'): Int64Index([43], dtype='int64'),
 ('中国', '重庆', '电子商务'): Int64Index([363], dtype='int64'),
 ('中国', '重庆', '软件与服务'): Int64Index([261], dtype='int64'),
 ('中国', '金华', '新能源汽车'): Int64Index([381], dtype='int64'),
 ('中国', '青岛', '物流'): Int64Index([246], dtype='int64'),
 ('中国', '香港', '区块链'): Int64Index([150], dtype='int64'),
 ('中国', '香港', '物流'): Int64Index([379], dtype='int64'),
 ('中国', '香港', '电子商务'): Int64Index([237], dtype='int64'),
 ('中国', '香港', '金融科技'): Int64Index([273, 475], dtype='int64'),
 ('以色列', '特拉维夫', '云计算'): Int64Index([178, 190], dtype='int64'),
 ('以色列', '特拉维夫', '生命科学'): Int64Index([364], dtype='int64'),
 ('以色列', '耐斯兹敖那', '云计算'): Int64Index([310], dtype='int64'),
 ('以色列', '耶路撒冷', '云计算'): Int64Index([384], dtype='int64'),
 ('以色列', '耶路撒冷', '人工智能'): Int64Index([415], dtype='int64'),
 ('以色列', '雷霍沃特', '软件与服务'): Int64Index([184], dtype='int64'),
 ('卢森堡', '卢森堡', '电子商务'): Int64Index([342], dtype='int64'),
 ('印度', '古尔冈', '共享经济'): Int64Index([52], dtype='int64'),
 ('印度', '古尔冈', '新能源'): Int64Index([206], dtype='int64'),
 ('印度', '古尔冈', '物流'): Int64Index([81, 163, 432], dtype='int64'),
 ('印度', '古尔冈', '电子商务'): Int64Index([437], dtype='int64'),
 ('印度', '古尔冈', '金融科技'): Int64Index([422], dtype='int64'),
 ('印度', '孟买', '游戏'): Int64Index([323], dtype='int64'),
 ('印度', '新德里', '即时通讯'): Int64Index([347], dtype='int64'),
 ('印度', '班加罗尔', '共享经济'): Int64Index([45, 410], dtype='int64'),
 ('印度', '班加罗尔', '大数据'): Int64Index([192], dtype='int64'),
 ('印度', '班加罗尔', '教育科技'): Int64Index([42], dtype='int64'),
 ('印度', '班加罗尔', '新零售'): Int64Index([287], dtype='int64'),
 ('印度', '班加罗尔', '物流'): Int64Index([123], dtype='int64'),
 ('印度', '班加罗尔', '电子商务'): Int64Index([425, 465], dtype='int64'),
 ('印度', '班加罗尔', '软件与服务'): Int64Index([361], dtype='int64'),
 ('印度', '艾哈迈达巴德', '金融科技'): Int64Index([146], dtype='int64'),
 ('印度', '诺伊达', '电子商务'): Int64Index([113], dtype='int64'),
 ('印度', '诺伊达', '金融科技'): Int64Index([23], dtype='int64'),
 ('印度尼西亚', '雅加达', '共享经济'): Int64Index([22], dtype='int64'),
 ('印度尼西亚', '雅加达', '电子商务'): Int64Index([39, 74, 294], dtype='int64'),
 ('哥伦比亚', '波哥大', '物流'): Int64Index([427], dtype='int64'),
 ('巴西', '圣保罗', '健康科技'): Int64Index([344], dtype='int64'),
 ('巴西', '圣保罗', '物流'): Int64Index([358, 389], dtype='int64'),
 ('巴西', '圣保罗', '金融科技'): Int64Index([66], dtype='int64'),
 ('德国', '巴登符腾堡州', '生命科学'): Int64Index([160], dtype='int64'),
 ('德国', '慕尼黑', '电子商务'): Int64Index([169], dtype='int64'),
 ('德国', '柏林', '电子商务'): Int64Index([56, 339, 411], dtype='int64'),
 ('德国', '柏林', '金融科技'): Int64Index([108], dtype='int64'),
 ('德国', '汉堡', '电子商务'): Int64Index([269], dtype='int64'),
 ('新加坡', '新加坡', '共享经济'): Int64Index([15], dtype='int64'),
 ('新加坡', '新加坡', '电子商务'): Int64Index([50], dtype='int64'),
 ('日本', '东京', '人工智能'): Int64Index([202], dtype='int64'),
 ('日本', '东京', '区块链'): Int64Index([388], dtype='int64'),
 ('法国', '巴黎', '人工智能'): Int64Index([396], dtype='int64'),
 ('法国', '巴黎', '健康科技'): Int64Index([320], dtype='int64'),
 ('法国', '巴黎', '共享经济'): Int64Index([149], dtype='int64'),
 ('法国', '巴黎', '媒体和娱乐'): Int64Index([317], dtype='int64'),
 ('澳大利亚', '悉尼', '云计算'): Int64Index([88], dtype='int64'),
 ('爱尔兰', '都柏林', '云计算'): Int64Index([182], dtype='int64'),
 ('爱沙尼亚', '塔林', '共享经济'): Int64Index([290], dtype='int64'),
 ('瑞典', '斯德哥尔摩', '新能源'): Int64Index([196], dtype='int64'),
 ('瑞典', '斯德哥尔摩', '金融科技'): Int64Index([62], dtype='int64'),
 ('瑞士', '巴塞尔', '生命科学'): Int64Index([36], dtype='int64'),
 ('瑞士', '楚格', '区块链'): Int64Index([167], dtype='int64'),
 ('瑞士', '洛桑市', '虚拟与增强现实'): Int64Index([400], dtype='int64'),
 ('美国', '-', '云计算'): Int64Index([357], dtype='int64'),
 ('美国', '-', '消费品'): Int64Index([217], dtype='int64'),
 ('美国', 'Burlington Massachussets', '3D印刷'): Int64Index([165], dtype='int64'),
 ('美国', 'Emerville', '网络安全'): Int64Index([38], dtype='int64'),
 ('美国', 'Foster City', '人工智能'): Int64Index([135], dtype='int64'),
 ('美国', 'Guilford', '健康科技'): Int64Index([295], dtype='int64'),
 ('美国', 'Harrisburg', '人工智能'): Int64Index([33], dtype='int64'),
 ('美国', 'Plantation', '虚拟与增强现实'): Int64Index([44], dtype='int64'),
 ('美国', 'Stafford', '新能源'): Int64Index([399], dtype='int64'),
 ('美国', '亚特兰大', '健康科技'): Int64Index([210], dtype='int64'),
 ('美国', '亚特兰大', '新能源'): Int64Index([435], dtype='int64'),
 ('美国', '亚特兰大', '网络安全'): Int64Index([413], dtype='int64'),
 ('美国', '亚特兰大', '金融科技'): Int64Index([373], dtype='int64'),
 ('美国', '伯班克', '媒体和娱乐'): Int64Index([213], dtype='int64'),
 ('美国', '克利尔沃特', '网络安全'): Int64Index([376], dtype='int64'),
 ('美国', '加迪纳', '新能源汽车'): Int64Index([59], dtype='int64'),
 ('美国', '匹兹堡', '共享经济'): Int64Index([40], dtype='int64'),
 ('美国', '半月湾', '物流'): Int64Index([492], dtype='int64'),
 ('美国', '华盛顿', '人工智能'): Int64Index([138], dtype='int64'),
 ('美国', '华盛顿', '媒体和娱乐'): Int64Index([471], dtype='int64'),
 ('美国', '卡尔弗城', '新零售'): Int64Index([447], dtype='int64'),
 ('美国', '卡尔弗城', '生命科学'): Int64Index([193], dtype='int64'),
 ('美国', '卡平特里亚', '房地产科技'): Int64Index([115], dtype='int64'),
 ('美国', '哥伦布', '金融科技'): Int64Index([434], dtype='int64'),
 ('美国', '圣何塞', '云计算'): Int64Index([308], dtype='int64'),
 ('美国', '圣何塞', '人工智能'): Int64Index([84], dtype='int64'),
 ('美国', '圣克拉拉', '云计算'): Int64Index([405], dtype='int64'),
 ('美国', '圣克拉拉', '人工智能'): Int64Index([444], dtype='int64'),
 ('美国', '圣卡洛斯', '大数据'): Int64Index([394], dtype='int64'),
 ('美国', '圣地亚哥', '人工智能'): Int64Index([436, 463], dtype='int64'),
 ('美国', '圣地亚哥', '生命科学'): Int64Index([21, 355], dtype='int64'),
 ('美国', '圣塔莫尼卡', '健康科技'): Int64Index([98], dtype='int64'),
 ('美国', '圣塔莫尼卡', '共享经济'): Int64Index([148], dtype='int64'),
 ('美国', '圣塔莫尼卡', '消费品'): Int64Index([455], dtype='int64'),
 ('美国', '圣塔莫尼卡', '电子商务'): Int64Index([331], dtype='int64'),
 ('美国', '圣布鲁诺', '云计算'): Int64Index([170], dtype='int64'),
 ('美国', '圣马特奥', '共享经济'): Int64Index([186], dtype='int64'),
 ('美国', '圣马特奥', '大数据'): Int64Index([71], dtype='int64'),
 ('美国', '圣马特奥', '游戏'): Int64Index([118], dtype='int64'),
 ('美国', '坎布里奇', '人工智能'): Int64Index([161], dtype='int64'),
 ('美国', '坎布里奇', '生命科学'): Int64Index([61], dtype='int64'),
 ('美国', '坎贝尔', '新能源'): Int64Index([302], dtype='int64'),
 ('美国', '埃尔塞贡多', '电子商务'): Int64Index([453], dtype='int64'),
 ('美国', '夏洛特市', '大数据'): Int64Index([461], dtype='int64'),
 ('美国', '夏洛特市', '金融科技'): Int64Index([283], dtype='int64'),
 ('美国', '奥克兰', '金融科技'): Int64Index([188], dtype='int64'),
 ('美国', '奥斯汀', '新零售'): Int64Index([375], dtype='int64'),
 ('美国', '奥斯汀', '金融科技'): Int64Index([191], dtype='int64'),
 ('美国', '尔湾', '健康科技'): Int64Index([277], dtype='int64'),
 ('美国', '山景城', '即时通讯'): Int64Index([452], dtype='int64'),
 ('美国', '山景城', '媒体和娱乐'): Int64Index([204], dtype='int64'),
 ('美国', '山景城', '教育科技'): Int64Index([312, 466], dtype='int64'),
 ('美国', '山景城', '物流'): Int64Index([222], dtype='int64'),
 ('美国', '山景城', '生命科学'): Int64Index([137], dtype='int64'),
 ('美国', '帕洛阿尔托', '云计算'): Int64Index([92], dtype='int64'),
 ('美国', '帕洛阿尔托', '人工智能'): Int64Index([143], dtype='int64'),
 ('美国', '帕洛阿尔托', '即时通讯'): Int64Index([448], dtype='int64'),
 ('美国', '帕洛阿尔托', '大数据'): Int64Index([17], dtype='int64'),
 ('美国', '帕洛阿尔托', '游戏'): Int64Index([51, 140], dtype='int64'),
 ('美国', '帕洛阿尔托', '电子商务'): Int64Index([60, 75], dtype='int64'),
 ('美国', '帕洛阿尔托', '金融科技'): Int64Index([156, 288], dtype='int64'),
 ('美国', '底特律', '电子商务'): Int64Index([445], dtype='int64'),
 ('美国', '斯科茨代尔', '消费品'): Int64Index([195], dtype='int64'),
 ('美国',
  '旧金山',
  '云计算'): Int64Index([70, 119, 142, 174, 208, 219, 272, 282, 319, 341, 397, 460, 470,
             474],
            dtype='int64'),
 ('美国', '旧金山', '人工智能'): Int64Index([307, 450], dtype='int64'),
 ('美国', '旧金山', '健康科技'): Int64Index([298, 412], dtype='int64'),
 ('美国', '旧金山', '共享经济'): Int64Index([5, 462], dtype='int64'),
 ('美国', '旧金山', '区块链'): Int64Index([29, 53, 289], dtype='int64'),
 ('美国', '旧金山', '即时通讯'): Int64Index([168, 194, 362], dtype='int64'),
 ('美国', '旧金山', '大数据'): Int64Index([94], dtype='int64'),
 ('美国', '旧金山', '媒体和娱乐'): Int64Index([117], dtype='int64'),
 ('美国', '旧金山', '房地产科技'): Int64Index([443], dtype='int64'),
 ('美国', '旧金山', '新零售'): Int64Index([276], dtype='int64'),
 ('美国', '旧金山', '机器人'): Int64Index([109], dtype='int64'),
 ('美国', '旧金山', '消费品'): Int64Index([4, 198], dtype='int64'),
 ('美国', '旧金山', '游戏'): Int64Index([126], dtype='int64'),
 ('美国', '旧金山', '物流'): Int64Index([18, 31, 97, 201, 374], dtype='int64'),
 ('美国', '旧金山', '电子商务'): Int64Index([28, 67, 280, 348, 457], dtype='int64'),
 ('美国', '旧金山', '网络安全'): Int64Index([306, 391], dtype='int64'),
 ('美国', '旧金山', '虚拟与增强现实'): Int64Index([65], dtype='int64'),
 ('美国',
  '旧金山',
  '金融科技'): Int64Index([9, 58, 72, 83, 86, 114, 159, 173], dtype='int64'),
 ('美国', '普利茅斯', '新能源汽车'): Int64Index([54], dtype='int64'),
 ('美国', '普若佛市', '人工智能'): Int64Index([179], dtype='int64'),
 ('美国', '普莱森顿', '生命科学'): Int64Index([264], dtype='int64'),
 ('美国', '杭廷顿海滩', '航天'): Int64Index([433], dtype='int64'),
 ('美国', '格兰岱尔市', '云计算'): Int64Index([209], dtype='int64'),
 ('美国', '格兰岱尔市', '教育科技'): Int64Index([271], dtype='int64'),
 ('美国', '森尼维耳市', '云计算'): Int64Index([324, 367], dtype='int64'),
 ('美国', '森尼维耳市', '人工智能'): Int64Index([456], dtype='int64'),
 ('美国', '森尼维耳市', '网络安全'): Int64Index([360], dtype='int64'),
 ('美国', '森尼维耳市', '软件与服务'): Int64Index([203], dtype='int64'),
 ('美国', '沃尔瑟姆', '云计算'): Int64Index([270], dtype='int64'),
 ('美国', '沃尔瑟姆', '健康科技'): Int64Index([166], dtype='int64'),
 ('美国', '波士顿', '云计算'): Int64Index([417], dtype='int64'),
 ('美国', '波士顿', '人工智能'): Int64Index([315], dtype='int64'),
 ('美国', '波士顿', '区块链'): Int64Index([90], dtype='int64'),
 ('美国', '波士顿', '游戏'): Int64Index([322], dtype='int64'),
 ('美国', '波士顿', '生命科学'): Int64Index([340], dtype='int64'),
 ('美国', '波士顿', '电子商务'): Int64Index([330], dtype='int64'),
 ('美国', '波士顿', '软件与服务'): Int64Index([316], dtype='int64'),
 ('美国', '波士顿', '金融科技'): Int64Index([125], dtype='int64'),
 ('美国', '洛杉矶', '媒体和娱乐'): Int64Index([16], dtype='int64'),
 ('美国', '洛杉矶', '电子商务'): Int64Index([493], dtype='int64'),
 ('美国', '洛杉矶', '航天'): Int64Index([7], dtype='int64'),
 ('美国', '盐湖城', '大数据'): Int64Index([346], dtype='int64'),
 ('美国', '纳什维尔', '健康科技'): Int64Index([121], dtype='int64'),
 ('美国', '纽约', '云计算'): Int64Index([3, 180, 211, 212], dtype='int64'),
 ('美国', '纽约', '人工智能'): Int64Index([41, 162, 489], dtype='int64'),
 ('美国', '纽约', '健康科技'): Int64Index([112, 221], dtype='int64'),
 ('美国', '纽约', '共享经济'): Int64Index([8], dtype='int64'),
 ('美国', '纽约', '大数据'): Int64Index([309], dtype='int64'),
 ('美国', '纽约', '媒体和娱乐'): Int64Index([151], dtype='int64'),
 ('美国', '纽约', '房地产科技'): Int64Index([472], dtype='int64'),
 ('美国', '纽约', '新零售'): Int64Index([284, 300], dtype='int64'),
 ('美国', '纽约', '消费品'): Int64Index([343, 420], dtype='int64'),
 ('美国', '纽约', '物流'): Int64Index([171], dtype='int64'),
 ('美国', '纽约', '电子商务'): Int64Index([57, 382, 395, 430], dtype='int64'),
 ('美国', '纽约', '软件与服务'): Int64Index([449], dtype='int64'),
 ('美国', '纽约', '金融科技'): Int64Index([185, 404], dtype='int64'),
 ('美国', '罗利', '大数据'): Int64Index([301], dtype='int64'),
 ('美国', '芝加哥', '人工智能'): Int64Index([216], dtype='int64'),
 ('美国', '芝加哥', '生命科学'): Int64Index([124], dtype='int64'),
 ('美国', '芝加哥', '金融科技'): Int64Index([144, 426], dtype='int64'),
 ('美国', '苗必达', '新能源'): Int64Index([469], dtype='int64'),
 ('美国', '菲尼克斯', '新能源汽车'): Int64Index([406], dtype='int64'),
 ('美国', '菲蒙市', '人工智能'): Int64Index([200], dtype='int64'),
 ('美国', '萨默维尔市', '3D印刷'): Int64Index([335], dtype='int64'),
 ('美国', '西雅图', '云计算'): Int64Index([416], dtype='int64'),
 ('美国', '西雅图', '物流'): Int64Index([311], dtype='int64'),
 ('美国', '贝尔维尤', '电子商务'): Int64Index([409], dtype='int64'),
 ('美国', '达拉斯', '生命科学'): Int64Index([68], dtype='int64'),
 ('美国', '迈阿密', '房地产科技'): Int64Index([419], dtype='int64'),
 ('美国', '门洛帕克', '房地产科技'): Int64Index([104], dtype='int64'),
 ('美国', '门洛帕克', '生命科学'): Int64Index([30], dtype='int64'),
 ('美国', '门洛帕克', '金融科技'): Int64Index([32], dtype='int64'),
 ('美国', '阿拉米达', '新能源'): Int64Index([440], dtype='int64'),
 ('美国', '阿林顿', '航天'): Int64Index([111], dtype='int64'),
 ('美国', '雷德伍德城', '3D印刷'): Int64Index([155], dtype='int64'),
 ('美国', '雷德伍德城', '云计算'): Int64Index([329, 366, 446], dtype='int64'),
 ('美国', '雷德伍德城', '人工智能'): Int64Index([296], dtype='int64'),
 ('美国', '雷德伍德城', '健康科技'): Int64Index([175, 424], dtype='int64'),
 ('美国', '雷德伍德城', '新零售'): Int64Index([176], dtype='int64'),
 ('美国', '雷德伍德城', '软件与服务'): Int64Index([293], dtype='int64'),
 ('芬兰', '赫尔辛基', '消费品'): Int64Index([349], dtype='int64'),
 ('英国', '伦敦', '人工智能'): Int64Index([145], dtype='int64'),
 ('英国', '伦敦', '游戏'): Int64Index([177], dtype='int64'),
 ('英国', '伦敦', '物流'): Int64Index([164], dtype='int64'),
 ('英国', '伦敦', '金融科技'): Int64Index([73, 82, 107, 110, 157, 207], dtype='int64'),
 ('英国', '布里斯托尔', '人工智能'): Int64Index([172], dtype='int64'),
 ('英国', '布里斯托尔', '新能源'): Int64Index([418], dtype='int64'),
 ('英国', '曼彻斯特', '电子商务'): Int64Index([55], dtype='int64'),
 ('英国', '牛津', '生命科学'): Int64Index([197], dtype='int64'),
 ('菲律宾', '马卡迪', '房地产科技'): Int64Index([431], dtype='int64'),
 ('西班牙', '马德里', '共享经济'): Int64Index([297], dtype='int64'),
 ('阿根廷', '布宜诺斯艾利斯', '云计算'): Int64Index([281], dtype='int64'),
 ('韩国', '城南市', '游戏'): Int64Index([49], dtype='int64'),
 ('韩国', '首尔', '物流'): Int64Index([129], dtype='int64'),
 ('韩国', '首尔', '电子商务'): Int64Index([26, 458, 479], dtype='int64'),
 ('韩国', '首尔', '金融科技'): Int64Index([459], dtype='int64'),
 ('马耳他', '-', '区块链'): Int64Index([147], dtype='int64')}

### 数据感

In [26]:
 df.groupby ( by = ['国家','行业'] ) \
             .agg ({ "估值（亿人民币）":["sum","mean"], \
                     "成立年份":["max","min"],}) \
             .sort_values ( by = [("估值（亿人民币）","sum")], ascending = False) \
             .rename ( columns = {"sum":"总和", "mean":"均值", "count":"数量", "max":"最新", "min":"最早"} )

           估值（亿人民币）              成立年份
                 总和          均值    最新    最早
国家   行业
中国   金融科技     17960  816.363636  2018  2002
     媒体和娱乐     8230  484.117647  2015  2003
美国   云计算       6880  215.000000  2015  2000
     共享经济      5670  945.000000  2017  2008
     金融科技      5020  239.047619  2017  2000
...             ...         ...   ...   ...
日本   区块链         70   70.000000  2014  2014
法国   人工智能        70   70.000000  2016  2016
     媒体和娱乐       70   70.000000  2006  2006
爱沙尼亚 共享经济        70   70.000000  2013  2013
法国   健康科技        70   70.000000  2013  2013

[103 rows x 4 columns]

## 总结

*